import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';
import { Alert } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { translateTexts } from '../api/translation';

const TRANSLATION_VERSION = '1.3'; // 번역 데이터 버전

const ko = {
  greeting: '안녕하세요',
  suffixNim: '님',
  todayWork: '오늘의 근무',
  scheduled: '근무 예정',
  inProgress: '근무중',
  completed: '근무 완료',
  substituteReq: '대타 요청중',
  offDay: '휴무',
  weeklyHours: '이번 주 근무 시간',
  weeklySalary: '이번 주 예상 급여',
  subReqAlertTitle: '새로운 대타 요청',
  subReqAlertDesc: '김민준 님의 근무에 대타 지원이 필요합니다.',
  applyBtn: '지원하기',
  rejectBtn: '거절',
  latestNotices: '최신 공지사항',
  viewAll: '전체보기',
  noNotices: '등록된 공지사항이 없습니다.',
  qrCheckIn: 'QR 체크인',
  defaultUserName: '사용자',
  admin: '관리자',
  staff: '직원',
  myInfo: '내 정보',
  profileEdit: '프로필 수정',
  contract: '근로계약서',
  healthCert: '보건증',
  appSettings: '앱 설정',
  themeMode: '테마 모드',
  languageSetting: '언어 설정',
  pushAlert: '푸시 알림',
  logout: '로그아웃',
  withdrawBtn: '회원 탈퇴',
  withdrawConfirmTitle: '회원 탈퇴 확인',
  withdrawConfirmMsg: '정말로 탈퇴하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
  cancel: '취소',
  confirm: '확인',
  withdrawSuccessTitle: '탈퇴 완료',
  withdrawSuccessMsg: '회원 탈퇴가 완료되었습니다. 이용해주셔서 감사합니다.',
  themeSettings: '테마 설정',
  langSettings: '언어 설정',
  employeeManagement: '직원 관리',
  monthlySchedule: '월간 근무표',
  payroll: '급여 정산',
  internalBoard: '사내 게시판',
  adminDashboard: '관리자 대시보드',
  brand: '브랜드',
  branch: '지점',
  currentlyWorking: '현재 근무중',
  requestProcessing: '요청 처리',
  selectBranch: '지점 선택',
  addNewBranch: '+ 새 지점 추가',
  close: '닫기',
  findSubstitute: '대타 찾기',
  myPaystub: '나의 급여 명세서',
  mySubstituteHistory: '나의 대타 내역',
  storeManagement: '매장 관리',
  storeInfoEdit: '매장 정보 수정',
  healthCertManagement: '보건증 관리',
  contractManagement: '근로계약서 관리',
  leaveRequestManagement: '휴무 신청 관리',
  lineConnect: 'LINE 연동하기',
  lightMode: '라이트 모드',
  darkMode: '다크 모드',
  systemSetting: '시스템 설정',
  writer: '작성자',
  views: '조회수',
  boardDetailTitle: '게시글 상세',
  unpin: '상단 고정 해제',
  pin: '상단 고정',
  comments: '댓글',
  noComments: '아직 댓글이 없습니다.',
  addCommentPlaceholder: '댓글을 입력하세요...',
  register: '등록',
  commentEmptyTitle: '댓글 오류',
  commentEmptyMsg: '댓글 내용을 입력해주세요.',
  deleteCommentConfirmTitle: '댓글 삭제',
  deleteCommentConfirmMsg: '이 댓글을 정말 삭제하시겠습니까?',
  deleteCommentSuccessTitle: '삭제 완료',
  deleteCommentSuccessMsg: '댓글이 삭제되었습니다.',
  unknown: '알 수 없음',
  checkIn: '출근',
  checkOut: '퇴근',
  expectedDailyWage: '예상 일급',
  currency: '원',
  noScheduleToday: '오늘은 예정된 근무가 없습니다.',
  notifListTitle: '알림 목록',
  markAllRead: '모두 읽음',
  delete: '삭제',
  weeklyDetailTitle: '주간 근무 상세',
  noDetails: '상세 내역을 불러올 수 없습니다.',
  totalWorkDays: '근무일',
  daysUnit: '일',
  totalWorkHours: '총 시간',
  hoursUnit: '시간',
  appliedRate: '적용 시급',
  dailyWorkHistory: '일별 근무 내역',
  noWeeklyWorkHistory: '이번 주 근무 기록이 없습니다.',
  alert: '알림',
  titleContentRequired: '제목과 내용을 모두 입력해주세요.',
  success: '성공',
  postEditSuccess: '게시글이 성공적으로 수정되었습니다.',
  newNotice: '새로운 공지사항 등록',
  notice: '공지사항',
  alertFailed: '알림 실패',
  pushAlertFailed: '푸시 알림을 보내는 데 실패했습니다.',
  postCreateSuccess: '게시글이 성공적으로 등록되었습니다.',
  editPost: '글 수정하기',
  writeNewPost: '새 글 쓰기',
  selectCategory: '카테고리 선택',
  title: '제목',
  titlePlaceholder: '제목을 입력하세요',
  content: '내용',
  contentPlaceholder: '내용을 자세히 작성해주세요.',
  editComplete: '수정하기',
  createComplete: '등록하기',
  suggestion: '건의사항',
  lost_found: '분실물',
  free_board: '자유게시판',
  leaveRequest: '휴무 신청 대기중',
  requestComplete: '신청 완료',
  requestSentToAdmin: '점주에게 요청이 전송되었습니다.',
  unassigned: '배정 안됨',
  requestLeave: '휴가 신청',
  requestSubstitute: '대타 신청',
  monthlyView: '월간 보기',
  newShift: '새 근무',
  noSchedule: '예정된 근무가 없습니다.',
  leaveReasonPlaceholder: '휴가 사유를 입력해주세요.',
  substituteReasonPlaceholder: '대타 요청 사유를 입력해주세요.',
  substituteApplyTitle: '대타 지원',
  substituteApplyMsg: '이 근무에 대타로 지원하시겠습니까?',
  applySuccess: '지원이 완료되었습니다.',
  error: '오류',
  errorApplySubstitute: '지원 중 오류가 발생했습니다.',
  myRequest: '내가 올린 요청',
  myApplication: '내가 지원한 요청',
  substituteRequests: '대타 구해요',
  history: '내역',
  noSubstituteRequests: '현재 올라온 대타 요청이 없습니다.',
  noHistory: '요청 또는 지원 내역이 없습니다.',
  todaySchedule: '오늘의 스케줄',
  morning: '오전',
  afternoon: '오후',
  closing: '마감',
  sun: '일',
  mon: '월',
  tue: '화',
  wed: '수',
  thu: '목',
  fri: '금',
  sat: '토',
  selectEmployee: '직원을 선택해주세요.',
  editShiftSuccess: '근무 수정 완료',
  addShiftSuccess: '새 근무 추가 완료',
  deleteConfirmTitle: '삭제 확인',
  deleteConfirmMsg: '이 근무를 정말 삭제하시겠습니까?',
  deleteShiftSuccess: '근무 삭제 완료',
  editShift: '근무 수정',
  addShift: '새 근무 추가',
  selectEmployeePlaceholder: '직원을 선택하세요...',
  date: '날짜',
  startTime: '시작 시간',
  endTime: '종료 시간',
  save: '저장',
  approveRequestTitle: '요청 승인',
  approveRequestMsg: '이 요청을 승인하시겠습니까?',
  approve: '승인',
  approvalComplete: '승인 완료',
  denyRequestTitle: '요청 거절',
  denyRequestMsg: '이 요청을 거절하시겠습니까?',
  deny: '거절',
  denialComplete: '거절 처리 완료',
  leave: '휴무',
  substitute: '대타',
  employee: '직원',
  workTime: '근무 시간',
  reason: '사유',
  requestManagement: '요청 관리',
  noRequests: '처리할 요청이 없습니다.',
  badgeNew: '새글',
  badgeImportant: '중요',
  saveCompleteTitle: '저장 완료',
  saveCompleteMsg: '개인정보가 성공적으로 수정되었습니다.',
  editFailTitle: '수정 실패',
  editFailMsg: '개인정보 수정 중 오류가 발생했습니다.',
  accountInfoReadonly: '계정 정보 (수정 불가)',
  idLabel: '아이디',
  branchLabel: '근무 매장',
  roleLabel: '권한',
  adminRole: '관리자',
  staffRole: '직원',
  myInfoSection: '개인정보 수정',
  nameLabel: '이름',
  namePlaceholder: '이름을 입력하세요',
  phoneLabel: '전화번호',
  phonePlaceholder: '전화번호를 입력하세요',
  changePasswordSection: '비밀번호 변경',
  currentPasswordLabel: '현재 비밀번호',
  currentPasswordPlaceholder: '현재 비밀번호 입력',
  newPasswordLabel: '새 비밀번호',
  newPasswordPlaceholder: '새 비밀번호 입력',
  editCompleteBtn: '수정 완료',
  subReqConfirmTitle: '대타 신청 확인',
  subReqConfirmMsg: '이 근무에 대타 지원을 하시겠습니까?',
  subApplySuccessTitle: '지원 완료',
  subApplySuccessMsg: '대타 지원이 정상적으로 완료되었습니다.',
  subPointUnit: 'P',
  subPointTotal: '누적 포인트',
  subEmptyReq: '등록된 대타 요청이 없습니다.',
  subEmptyHist: '대타 내역이 존재하지 않습니다.',
  subTabRequest: '대타 요청',
  subTabHistory: '매칭 내역',
  valid: '유효함',
  pendingApproval: '승인 대기중',
  expired: '만료됨',
  needsRenewal: '갱신 필요',
  expiryDate: '만료일',
  uploadNew: '새로운 사진 업로드',
  workPlace: '근무지',
  startDate: '시작일',
  wage: '시급',
  boardTabAll: '전체',
  boardTabNotice: '공지사항',
  boardTabMenu: '건의사항',
  boardTabEvent: '자유게시판',
  boardTabManual: '매뉴얼',
  boardTabLost: '분실물',
  boardTabChecklist: '체크리스트',
  more: '더보기',
  substituteTitle: '대타 구하기',
};

const en: TranslationData = {
  greeting: 'Hello',
  suffixNim: '',
  todayWork: "Today's Shift",
  scheduled: 'Scheduled',
  inProgress: 'In Progress',
  completed: 'Completed',
  substituteReq: 'Substitute Requested',
  offDay: 'Off',
  weeklyHours: 'Weekly Hours',
  weeklySalary: 'Estimated Weekly Pay',
  subReqAlertTitle: 'New Substitute Request',
  subReqAlertDesc: 'A substitute is needed for Minjun Kim\'s shift.',
  applyBtn: 'Apply',
  rejectBtn: 'Reject',
  latestNotices: 'Latest Announcements',
  viewAll: 'View All',
  noNotices: 'No announcements registered.',
  qrCheckIn: 'QR Check-in',
  defaultUserName: 'User',
  admin: 'Admin',
  staff: 'Staff',
  myInfo: 'My Info',
  profileEdit: 'Edit Profile',
  contract: 'Labor Contract',
  healthCert: 'Health Certificate',
  appSettings: 'App Settings',
  themeMode: 'Theme Mode',
  languageSetting: 'Language',
  pushAlert: 'Push Notifications',
  logout: 'Log Out',
  withdrawBtn: 'Delete Account',
  withdrawConfirmTitle: 'Confirm Account Deletion',
  withdrawConfirmMsg: 'Are you sure you want to delete your account? This action cannot be undone.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  withdrawSuccessTitle: 'Account Deleted',
  withdrawSuccessMsg: 'Your account has been deleted. Thank you for using our service.',
  themeSettings: 'Theme Settings',
  langSettings: 'Language Settings',
  employeeManagement: 'Employee Management',
  monthlySchedule: 'Monthly Schedule',
  payroll: 'Payroll Calculation',
  internalBoard: 'Internal Board',
  adminDashboard: 'Admin Dashboard',
  brand: 'Brand',
  branch: 'Branch',
  currentlyWorking: 'Currently Working',
  requestProcessing: 'Process Requests',
  selectBranch: 'Select Branch',
  addNewBranch: '+ Add New Branch',
  close: 'Close',
  findSubstitute: 'Find Substitute',
  myPaystub: 'My Paystub',
  mySubstituteHistory: 'My Substitute History',
  storeManagement: 'Store Management',
  storeInfoEdit: 'Edit Store Info',
  healthCertManagement: 'Health Certs',
  contractManagement: 'Contracts',
  leaveRequestManagement: 'Leave Requests',
  lineConnect: 'Connect LINE',
  lightMode: 'Light Mode',
  darkMode: 'Dark Mode',
  systemSetting: 'System Theme',
  writer: 'Writer',
  views: 'Views',
  boardDetailTitle: 'Post Detail',
  unpin: 'Unpin',
  pin: 'Pin to Top',
  comments: 'Comments',
  noComments: 'No comments yet.',
  addCommentPlaceholder: 'Enter a comment...',
  register: 'Register',
  commentEmptyTitle: 'Comment Error',
  commentEmptyMsg: 'Please enter comment content.',
  deleteCommentConfirmTitle: 'Delete Comment',
  deleteCommentConfirmMsg: 'Are you sure you want to delete this comment?',
  deleteCommentSuccessTitle: 'Deleted',
  deleteCommentSuccessMsg: 'Comment has been deleted.',
  unknown: 'Unknown',
  checkIn: 'Clock In',
  checkOut: 'Clock Out',
  expectedDailyWage: 'Estimated Daily Wage',
  currency: ' KRW',
  noScheduleToday: 'No shifts scheduled for today.',
  notifListTitle: 'Notifications',
  markAllRead: 'Mark All Read',
  delete: 'Delete',
  weeklyDetailTitle: 'Weekly Shift Detail',
  noDetails: 'Failed to load details.',
  totalWorkDays: 'Work Days',
  daysUnit: ' Days',
  totalWorkHours: 'Total Hours',
  hoursUnit: ' Hours',
  appliedRate: 'Applied Rate',
  dailyWorkHistory: 'Daily Work History',
  noWeeklyWorkHistory: 'No work history for this week.',
  alert: 'Alert',
  titleContentRequired: 'Please enter both title and content.',
  success: 'Success',
  postEditSuccess: 'Post has been successfully updated.',
  newNotice: 'Post New Announcement',
  notice: 'Announcement',
  alertFailed: 'Notification Failed',
  pushAlertFailed: 'Failed to send push notification.',
  postCreateSuccess: 'Post has been successfully registered.',
  editPost: 'Edit Post',
  writeNewPost: 'Write New Post',
  selectCategory: 'Select Category',
  title: 'Title',
  titlePlaceholder: 'Enter title',
  content: 'Content',
  contentPlaceholder: 'Please describe the details.',
  editComplete: 'Save Changes',
  createComplete: 'Publish',
  suggestion: 'Suggestion',
  lost_found: 'Lost & Found',
  free_board: 'Free Board',
  leaveRequest: 'Leave Requested',
  requestComplete: 'Request Completed',
  requestSentToAdmin: 'Request has been sent to the manager.',
  unassigned: 'Unassigned',
  requestLeave: 'Request Leave',
  requestSubstitute: 'Request Substitute',
  monthlyView: 'Monthly View',
  newShift: 'New Shift',
  noSchedule: 'No shifts scheduled.',
  leaveReasonPlaceholder: 'Please enter the reason for leave.',
  substituteReasonPlaceholder: 'Please enter the reason for substitute request.',
  substituteApplyTitle: 'Apply for Substitute',
  substituteApplyMsg: 'Do you want to apply for this shift?',
  applySuccess: 'Application completed.',
  error: 'Error',
  errorApplySubstitute: 'An error occurred during application.',
  myRequest: 'My Requests',
  myApplication: 'My Applications',
  substituteRequests: 'Substitute Needed',
  history: 'History',
  noSubstituteRequests: 'No substitute requests posted.',
  noHistory: 'No request or application history.',
  todaySchedule: "Today's Schedule",
  morning: 'Morning',
  afternoon: 'Afternoon',
  closing: 'Closing',
  sun: 'Sun',
  mon: 'Mon',
  tue: 'Tue',
  wed: 'Wed',
  thu: 'Thu',
  fri: 'Fri',
  sat: 'Sat',
  selectEmployee: 'Please select an employee.',
  editShiftSuccess: 'Shift updated successfully.',
  addShiftSuccess: 'New shift added successfully.',
  deleteConfirmTitle: 'Confirm Delete',
  deleteConfirmMsg: 'Are you sure you want to delete this shift?',
  deleteShiftSuccess: 'Shift deleted successfully.',
  editShift: 'Edit Shift',
  addShift: 'Add Shift',
  selectEmployeePlaceholder: 'Select employee...',
  date: 'Date',
  startTime: 'Start Time',
  endTime: 'End Time',
  save: 'Save',
  approveRequestTitle: 'Approve Request',
  approveRequestMsg: 'Do you want to approve this request?',
  approve: 'Approve',
  approvalComplete: 'Approval Completed',
  denyRequestTitle: 'Reject Request',
  denyRequestMsg: 'Do you want to reject this request?',
  deny: 'Reject',
  denialComplete: 'Rejection Completed',
  leave: 'Leave',
  substitute: 'Substitute',
  employee: 'Employee',
  workTime: 'Work Hours',
  reason: 'Reason',
  requestManagement: 'Request Management',
  noRequests: 'No requests to process.',
  badgeNew: 'New',
  badgeImportant: 'Important',
  saveCompleteTitle: 'Saved Successfully',
  saveCompleteMsg: 'Profile has been successfully updated.',
  editFailTitle: 'Save Failed',
  editFailMsg: 'An error occurred while updating profile.',
  accountInfoReadonly: 'Account Info (Read-only)',
  idLabel: 'ID',
  branchLabel: 'Branch',
  roleLabel: 'Role',
  adminRole: 'Admin',
  staffRole: 'Staff',
  myInfoSection: 'Edit Profile',
  nameLabel: 'Name',
  namePlaceholder: 'Enter name',
  phoneLabel: 'Phone',
  phonePlaceholder: 'Enter phone number',
  changePasswordSection: 'Change Password',
  currentPasswordLabel: 'Current Password',
  currentPasswordPlaceholder: 'Enter current password',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'Enter new password',
  editCompleteBtn: 'Update Profile',
  subReqConfirmTitle: 'Confirm Application',
  subReqConfirmMsg: 'Do you want to apply for this substitute shift?',
  subApplySuccessTitle: 'Applied',
  subApplySuccessMsg: 'Substitute application completed successfully.',
  subPointUnit: 'P',
  subPointTotal: 'Total Points',
  subEmptyReq: 'No substitute requests registered.',
  subEmptyHist: 'No substitute history.',
  subTabRequest: 'Sub Requests',
  subTabHistory: 'Matching History',
  valid: 'Valid',
  pendingApproval: 'Pending Approval',
  expired: 'Expired',
  needsRenewal: 'Needs Renewal',
  expiryDate: 'Expiry Date',
  uploadNew: 'Upload New Photo',
  workPlace: 'Work Place',
  startDate: 'Start Date',
  wage: 'Wage',
  boardTabAll: 'All',
  boardTabNotice: 'Notices',
  boardTabMenu: 'Suggestions',
  boardTabEvent: 'Free Board',
  boardTabManual: 'Manuals',
  boardTabLost: 'Lost & Found',
  boardTabChecklist: 'Checklist',
  more: 'More',
  substituteTitle: 'Find Substitutes',
};

const ja: TranslationData = {
  greeting: 'こんにちは',
  suffixNim: '様',
  todayWork: '今日の勤務',
  scheduled: '勤務予定',
  inProgress: '勤務中',
  completed: '勤務完了',
  substituteReq: '代打要請中',
  offDay: '休み',
  weeklyHours: '今週の勤務時間',
  weeklySalary: '今週の予想給与',
  subReqAlertTitle: '新しい代打要請',
  subReqAlertDesc: 'キム・ミンジュン様の勤務に代打応募が必要です。',
  applyBtn: '応募する',
  rejectBtn: '拒否',
  latestNotices: '最新のお知らせ',
  viewAll: 'すべて見る',
  noNotices: '登録されたお知らせがありません。',
  qrCheckIn: 'QRチェックイン',
  defaultUserName: 'ユーザー',
  admin: '管理者',
  staff: 'スタッフ',
  myInfo: 'マイページ',
  profileEdit: 'プロフィール編集',
  contract: '雇用契約書',
  healthCert: '検便・健康診断証',
  appSettings: 'アプリ設定',
  themeMode: 'テーマモード',
  languageSetting: '言語設定',
  pushAlert: 'プッシュ通知',
  logout: 'ログアウト',
  withdrawBtn: '退会する',
  withdrawConfirmTitle: '退会確認',
  withdrawConfirmMsg: '本当に退会しますか？この操作は取り消せません。',
  cancel: 'キャンセル',
  confirm: '確認',
  withdrawSuccessTitle: '退会完了',
  withdrawSuccessMsg: '退会が完了しました。ご利用いただきありがとうございました。',
  themeSettings: 'テーマ設定',
  langSettings: '言語設定',
  employeeManagement: '従業員管理',
  monthlySchedule: '月間シフト表',
  payroll: '給与計算',
  internalBoard: '社내掲示板',
  adminDashboard: '管理者ダッシュボード',
  brand: 'ブランド',
  branch: '店舗',
  currentlyWorking: '現在勤務中',
  requestProcessing: '申請処理',
  selectBranch: '店舗選択',
  addNewBranch: '+ 新規店舗追加',
  close: '閉じる',
  findSubstitute: '代打を探す',
  myPaystub: '給与明細書',
  mySubstituteHistory: '自分の代打履歴',
  storeManagement: '店舗管理',
  storeInfoEdit: '店舗情報修正',
  healthCertManagement: '健康診断証管理',
  contractManagement: '契約書管理',
  leaveRequestManagement: '休暇申請管理',
  lineConnect: 'LINE連携',
  lightMode: 'ライトモード',
  darkMode: 'ダークモード',
  systemSetting: 'システム設定',
  writer: '作成者',
  views: '閲覧数',
  boardDetailTitle: '投稿詳細',
  unpin: 'ピン留め解除',
  pin: 'ピン留め',
  comments: 'コメント',
  noComments: 'コメントはまだありません。',
  addCommentPlaceholder: 'コメントを入力してください...',
  register: '登録',
  commentEmptyTitle: 'コメントエラー',
  commentEmptyMsg: 'コメント内容を入力してください。',
  deleteCommentConfirmTitle: 'コメント削除',
  deleteCommentConfirmMsg: 'このコメントを本当に削除しますか？',
  deleteCommentSuccessTitle: '削除完了',
  deleteCommentSuccessMsg: 'コメントが削除されました。',
  unknown: '不明',
  checkIn: '出勤',
  checkOut: '退勤',
  expectedDailyWage: '予想日給',
  currency: ' 円',
  noScheduleToday: '本日の予定シフトはありません。',
  notifListTitle: '通知一覧',
  markAllRead: 'すべて既読にする',
  delete: '削除',
  weeklyDetailTitle: '週間勤務詳細',
  noDetails: '詳細履歴を読み込めませんでした。',
  totalWorkDays: '勤務日数',
  daysUnit: '日',
  totalWorkHours: '総時間',
  hoursUnit: '時間',
  appliedRate: '適用時給',
  dailyWorkHistory: '日別勤務内訳',
  noWeeklyWorkHistory: '今週の勤務記録がありません。',
  alert: '通知',
  titleContentRequired: 'タイトルと内容の両方を入力してください。',
  success: '成功',
  postEditSuccess: '投稿が正常に修正されました。',
  newNotice: '新規お知らせ登録',
  notice: 'お知らせ',
  alertFailed: '通知失敗',
  pushAlertFailed: 'プッシュ通知の送信に失敗しました。',
  postCreateSuccess: '投稿が正常に登録されました。',
  editPost: '投稿編集',
  writeNewPost: '新規投稿',
  selectCategory: 'カテゴリー選択',
  title: 'タイトル',
  titlePlaceholder: 'タイトルを入力してください',
  content: '内容',
  contentPlaceholder: '内容を詳しく記入してください。',
  editComplete: '修正する',
  createComplete: '登録する',
  suggestion: 'ご意見・提案',
  lost_found: '忘れ物',
  free_board: '自由掲示板',
  leaveRequest: '休暇申請保留中',
  requestComplete: '申請完了',
  requestSentToAdmin: '店舗管理者に申請が送信されました。',
  unassigned: '未割り当て',
  requestLeave: '休暇申請',
  requestSubstitute: '代打申請',
  monthlyView: '月間表示',
  newShift: '新規シフト',
  noSchedule: '予定されたシフトはありません。',
  leaveReasonPlaceholder: '休暇の理由を入力してください。',
  substituteReasonPlaceholder: '代打要請の理由を入力してください。',
  substituteApplyTitle: '代打応募',
  substituteApplyMsg: 'このシフトに代打として応募しますか？',
  applySuccess: '応募が完了しました。',
  error: 'エラー',
  errorApplySubstitute: '応募中にエラーが発生しました。',
  myRequest: '自分が作成した要請',
  myApplication: '自分が応募した要請',
  substituteRequests: '代打募集',
  history: '履歴',
  noSubstituteRequests: '現在募集中の代打はありません。',
  noHistory: '要請または応募の履歴がありません。',
  todaySchedule: '今日のスケジュール',
  morning: '午前',
  afternoon: '午後',
  closing: '締め',
  sun: '日',
  mon: '月',
  tue: '火',
  wed: '水',
  thu: '木',
  fri: '金',
  sat: '土',
  selectEmployee: '従業員を選択してください。',
  editShiftSuccess: 'シフトの更新が完了しました。',
  addShiftSuccess: '新規シフトの追加が完了しました。',
  deleteConfirmTitle: '削除の確認',
  deleteConfirmMsg: 'このシフトを本当に削除しますか？',
  deleteShiftSuccess: 'シフトが削除されました。',
  editShift: 'シフト編集',
  addShift: '新規シフト追加',
  selectEmployeePlaceholder: '従業員を選択してください...',
  date: '日付',
  startTime: '開始時間',
  endTime: '終了時間',
  save: '保存',
  approveRequestTitle: '申請承認',
  approveRequestMsg: 'この申請を承認しますか？',
  approve: '承認',
  approvalComplete: '承認が完了しました。',
  denyRequestTitle: '申請拒否',
  denyRequestMsg: 'この申請を拒否しますか？',
  deny: '拒否',
  denialComplete: '拒否処理が完了しました。',
  leave: '休暇',
  substitute: '代打',
  employee: '従業員',
  workTime: '勤務時間',
  reason: '理由',
  requestManagement: '申請管理',
  noRequests: '処理する申請はありません。',
  badgeNew: '新規',
  badgeImportant: '重要',
  saveCompleteTitle: '保存完了',
  saveCompleteMsg: '個人情報が正常に修正されました。',
  editFailTitle: '修正失敗',
  editFailMsg: '個人情報の修正中にエラーが発生しました。',
  accountInfoReadonly: 'アカウント情報（編集不可）',
  idLabel: 'ユーザーID',
  branchLabel: '勤務店舗',
  roleLabel: '権限',
  adminRole: '管理者',
  staffRole: 'スタッフ',
  myInfoSection: 'プロフィール編集',
  nameLabel: 'お名前',
  namePlaceholder: 'お名前を入力してください',
  phoneLabel: '電話番号',
  phonePlaceholder: '電話番号を入力してください',
  changePasswordSection: 'パスワード変更',
  currentPasswordLabel: '現在のパスワード',
  currentPasswordPlaceholder: '現在のパスワードを入力',
  newPasswordLabel: '新しいパスワード',
  newPasswordPlaceholder: '新しいパスワードを入力',
  editCompleteBtn: 'プロフィール更新',
  subReqConfirmTitle: '応募確認',
  subReqConfirmMsg: 'このシフトに代打応募しますか？',
  subApplySuccessTitle: '応募完了',
  subApplySuccessMsg: '代打応募が正常に完了しました。',
  subPointUnit: 'P',
  subPointTotal: '累計ポイント',
  subEmptyReq: '登録された代打要請はありません。',
  subEmptyHist: '代打履歴が存在しません。',
  subTabRequest: '代打要請',
  subTabHistory: 'マッチング履歴',
  valid: '有効',
  pendingApproval: '承認待ち',
  expired: '期限切れ',
  needsRenewal: '更新が必要',
  expiryDate: '有効期限',
  uploadNew: '写真をアップロード',
  workPlace: '勤務地',
  startDate: '開始日',
  wage: '時給',
  boardTabAll: 'すべて',
  boardTabNotice: 'お知らせ',
  boardTabMenu: 'ご意見箱',
  boardTabEvent: '自由掲示板',
  boardTabManual: 'マニュアル',
  boardTabLost: '忘れ物',
  boardTabChecklist: 'チェックリスト',
  more: 'もっと見る',
  substituteTitle: '代打を探す',
};

export type Language = '한국어' | 'English' | '日本語';
type TranslationData = typeof ko;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof TranslationData | string) => string;
  isTranslating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('한국어');
  const translations: { [key: string]: TranslationData } = { ko, en, ja };

  useEffect(() => {
    const loadLanguage = async () => {
      const savedLang = await AsyncStorage.getItem('language') as Language | null;
      if (savedLang) {
        setLanguageState(savedLang);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    if (lang === language) return;
    setLanguageState(lang);
    await AsyncStorage.setItem('language', lang);
  };

  const t = (key: keyof TranslationData | string): string => {
    const langCode = language === 'English' ? 'en' : language === '日本語' ? 'ja' : 'ko';
    const translationSet = translations[langCode] || translations.ko;
    return (translationSet as any)[key] || (translations.ko as any)[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTranslating: false }}>
      {children}
    </LanguageContext.Provider>
  );
};
