import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';
import { Alert } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { translateTexts } from '../api/translation';

const TRANSLATION_VERSION = '1.3'; // 번역 데이터 버전

const ko = {
  greeting: '안녕하세요',
  suffixNim: '님',
  todayWork: '오늘의 근무',
  todayAttendance: '오늘의 출퇴근 기록',
  notCheckedInYet: '출근 전',
  notCheckedOutYet: '퇴근 전 (근무 중)',
  viewMonthlyAttendance: '월별 출퇴근 내역 보기',
  noAttendanceToday: '오늘의 출퇴근 기록이 없습니다.',
  scheduled: '근무 예정',
  inProgress: '근무중',
  completed: '근무 완료',
  substituteReq: '대타 요청중',
  offDay: '휴무',
  statusWorking: '근무중',
  statusCompleted: '근무 완료',
  statusCheckedOut: '퇴근 완료',
  statusLate: '지각',
  statusEarlyLeave: '조퇴',
  statusAbsent: '결근',
  statusNormal: '정상',
  attendanceRecordSuffix: '님의 출퇴근 기록',
  detailedRecord: '상세 기록',
  noAttendanceMonth: '해당 월의 출퇴근 기록이 없습니다.',
  monthYearFormatPattern: 'yyyy년 M월',
  tabDashboard: '대시보드',
  tabSchedule: '근무 관리',
  tabEmployee: '직원 관리',
  tabMyPage: '내 정보',
  tabHome: '홈',
  tabScheduleStaff: '스케줄',
  tabNotification: '알림',
  weeklyHours: '이번 주 근무 시간',
  weeklySalary: '이번 주 예상 급여',
  subReqAlertTitle: '새로운 대타 요청',
  subReqAlertDesc: '김민준 님의 근무에 대타 지원이 필요합니다.',
  applyBtn: '지원하기',
  rejectBtn: '거절',
  latestNotices: '최신 공지사항',
  viewAll: '전체보기',
  noNotices: '등록된 공지사항이 없습니다.',
  qrCheckIn: 'QR 체크인',
  defaultUserName: '사용자',
  admin: '관리자',
  staff: '직원',
  myInfo: '내 정보',
  profileEdit: '프로필 수정',
  contract: '근로계약서',
  healthCert: '보건증',
  appSettings: '앱 설정',
  themeMode: '테마 모드',
  languageSetting: '언어 설정',
  pushAlert: '푸시 알림',
  logout: '로그아웃',
  withdrawBtn: '회원 탈퇴',
  withdrawConfirmTitle: '회원 탈퇴 확인',
  withdrawConfirmMsg: '정말로 탈퇴하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
  cancel: '취소',
  confirm: '확인',
  withdrawSuccessTitle: '탈퇴 완료',
  withdrawSuccessMsg: '회원 탈퇴가 완료되었습니다. 이용해주셔서 감사합니다.',
  themeSettings: '테마 설정',
  langSettings: '언어 설정',
  employeeManagement: '직원 관리',
  monthlySchedule: '월간 근무표',
  payroll: '급여 정산',
  internalBoard: '사내 게시판',
  adminDashboard: '관리자 대시보드',
  brand: '브랜드',
  branch: '지점',
  currentlyWorking: '현재 근무중',
  requestProcessing: '요청 처리',
  selectBranch: '지점 선택',
  addNewBranch: '+ 새 지점 추가',
  close: '닫기',
  findSubstitute: '대타 찾기',
  myPaystub: '나의 급여 명세서',
  mySubstituteHistory: '나의 대타 내역',
  storeManagement: '매장 관리',
  storeInfoEdit: '매장 정보 수정',
  healthCertManagement: '보건증 관리',
  contractManagement: '근로계약서 관리',
  leaveRequestManagement: '휴무 신청 관리',
  lineConnect: 'LINE 연동하기',
  lightMode: '라이트 모드',
  darkMode: '다크 모드',
  systemSetting: '시스템 설정',
  writer: '작성자',
  views: '조회수',
  boardDetailTitle: '게시글 상세',
  unpin: '상단 고정 해제',
  pin: '상단 고정',
  comments: '댓글',
  noComments: '아직 댓글이 없습니다.',
  addCommentPlaceholder: '댓글을 입력하세요...',
  register: '등록',
  commentEmptyTitle: '댓글 오류',
  commentEmptyMsg: '댓글 내용을 입력해주세요.',
  deleteCommentConfirmTitle: '댓글 삭제',
  deleteCommentConfirmMsg: '이 댓글을 정말 삭제하시겠습니까?',
  deleteCommentSuccessTitle: '삭제 완료',
  deleteCommentSuccessMsg: '댓글이 삭제되었습니다.',
  unknown: '알 수 없음',
  checkIn: '출근',
  checkOut: '퇴근',
  expectedDailyWage: '예상 일급',
  currency: '원',
  noScheduleToday: '오늘은 예정된 근무가 없습니다.',
  notifListTitle: '알림 목록',
  markAllRead: '모두 읽음',
  delete: '삭제',
  weeklyDetailTitle: '주간 근무 상세',
  noDetails: '상세 내역을 불러올 수 없습니다.',
  totalWorkDays: '근무일',
  daysUnit: '일',
  totalWorkHours: '총 시간',
  hoursUnit: '시간',
  appliedRate: '적용 시급',
  dailyWorkHistory: '일별 근무 내역',
  noWeeklyWorkHistory: '이번 주 근무 기록이 없습니다.',
  alert: '알림',
  titleContentRequired: '제목과 내용을 모두 입력해주세요.',
  success: '성공',
  postEditSuccess: '게시글이 성공적으로 수정되었습니다.',
  newNotice: '새로운 공지사항 등록',
  notice: '공지사항',
  alertFailed: '알림 실패',
  pushAlertFailed: '푸시 알림을 보내는 데 실패했습니다.',
  postCreateSuccess: '게시글이 성공적으로 등록되었습니다.',
  editPost: '글 수정하기',
  writeNewPost: '새 글 쓰기',
  selectCategory: '카테고리 선택',
  title: '제목',
  titlePlaceholder: '제목을 입력하세요',
  content: '내용',
  contentPlaceholder: '내용을 자세히 작성해주세요.',
  editComplete: '수정하기',
  createComplete: '등록하기',
  suggestion: '건의사항',
  lost_found: '분실물',
  free_board: '자유게시판',
  leaveRequest: '휴무 신청 대기중',
  requestComplete: '신청 완료',
  payrollTitle: '급여 정산 상세',
  estMonthlySalary: '이번 달 예상 급여',
  basePay: '기본급',
  holidayPay: '주휴수당',
  substituteBonus: '대타 수수료',
  dailyWageDetail: '일별 급여 내역',
  calculatingPayroll: '급여 내역을 계산 중입니다...',
  noWorkRecordThisMonth: '이번 달 근무 기록이 없습니다.',
  requestSentToAdmin: '점주에게 요청이 전송되었습니다.',
  unassigned: '배정 안됨',
  requestLeave: '휴가 신청',
  requestSubstitute: '대타 신청',
  monthlyView: '월간 보기',
  newShift: '새 근무',
  noSchedule: '예정된 근무가 없습니다.',
  leaveReasonPlaceholder: '휴가 사유를 입력해주세요.',
  substituteReasonPlaceholder: '대타 요청 사유를 입력해주세요.',
  substituteApplyTitle: '대타 지원',
  substituteApplyMsg: '이 근무에 대타로 지원하시겠습니까?',
  applySuccess: '지원이 완료되었습니다.',
  error: '오류',
  errorApplySubstitute: '지원 중 오류가 발생했습니다.',
  myRequest: '내가 올린 요청',
  myApplication: '내가 지원한 요청',
  substituteRequests: '대타 구해요',
  history: '내역',
  noSubstituteRequests: '현재 올라온 대타 요청이 없습니다.',
  noHistory: '요청 또는 지원 내역이 없습니다.',
  todaySchedule: '오늘의 스케줄',
  morning: '오전',
  afternoon: '오후',
  closing: '마감',
  sun: '일',
  mon: '월',
  tue: '화',
  wed: '수',
  thu: '목',
  fri: '금',
  sat: '토',
  selectEmployee: '직원을 선택해주세요.',
  editShiftSuccess: '근무 수정 완료',
  addShiftSuccess: '새 근무 추가 완료',
  deleteConfirmTitle: '삭제 확인',
  deleteConfirmMsg: '이 근무를 정말 삭제하시겠습니까?',
  deleteShiftSuccess: '근무 삭제 완료',
  editShift: '근무 수정',
  addShift: '새 근무 추가',
  selectEmployeePlaceholder: '직원을 선택하세요...',
  date: '날짜',
  startTime: '시작 시간',
  endTime: '종료 시간',
  save: '저장',
  approveRequestTitle: '요청 승인',
  approveRequestMsg: '이 요청을 승인하시겠습니까?',
  approve: '승인',
  approvalComplete: '승인 완료',
  denyRequestTitle: '요청 거절',
  denyRequestMsg: '이 요청을 거절하시겠습니까?',
  deny: '거절',
  denialComplete: '거절 처리 완료',
  leave: '휴무',
  substitute: '대타',
  employee: '직원',
  workTime: '근무 시간',
  reason: '사유',
  requestManagement: '요청 관리',
  noRequests: '처리할 요청이 없습니다.',
  badgeNew: '새글',
  badgeImportant: '중요',
  saveCompleteTitle: '저장 완료',
  saveCompleteMsg: '개인정보가 성공적으로 수정되었습니다.',
  editFailTitle: '수정 실패',
  editFailMsg: '개인정보 수정 중 오류가 발생했습니다.',
  accountInfoReadonly: '계정 정보 (수정 불가)',
  idLabel: '아이디',
  branchLabel: '근무 매장',
  roleLabel: '권한',
  adminRole: '관리자',
  staffRole: '직원',
  myInfoSection: '개인정보 수정',
  nameLabel: '이름',
  namePlaceholder: '이름을 입력하세요',
  phoneLabel: '전화번호',
  phonePlaceholder: '전화번호를 입력하세요',
  changePasswordSection: '비밀번호 변경',
  currentPasswordLabel: '현재 비밀번호',
  currentPasswordPlaceholder: '현재 비밀번호 입력',
  newPasswordLabel: '새 비밀번호',
  newPasswordPlaceholder: '새 비밀번호 입력',
  editCompleteBtn: '수정 완료',
  subReqConfirmTitle: '대타 신청 확인',
  subReqConfirmMsg: '이 근무에 대타 지원을 하시겠습니까?',
  subApplySuccessTitle: '지원 완료',
  subApplySuccessMsg: '대타 지원이 정상적으로 완료되었습니다.',
  subPointUnit: 'P',
  subPointTotal: '누적 포인트',
  subEmptyReq: '등록된 대타 요청이 없습니다.',
  subEmptyHist: '대타 내역이 존재하지 않습니다.',
  subTabRequest: '대타 요청',
  subTabHistory: '매칭 내역',
  loadSubstituteFail: '대타 정보 로드 실패',
  checkServerConnection: '서버 연결 상태를 확인해주세요.',
  applyFail: '지원 실패',
  applyFailDetail: '이미 지원했거나 서버 오류가 발생했습니다.',
  substituteApplyDefaultMsg: '대타 신청합니다.',
  substituteRoleDefault: '대타 근무',
  dateFormatPattern: 'M월 d일 (eee)',
  dateFormatMD: 'M월 d일',
  loadDataFail: '데이터를 불러오는데 실패했습니다.',
  appliedToPost: '{id}에 지원함',
  loadApplicantsFail: '지원자 목록을 불러오는 데 실패했습니다.',
  selectSubstitute: '대타 선택',
  selectSubstituteConfirm: '{name}님을 대타 근무자로 선택하시겠습니까? 관리자의 최종 승인이 필요합니다.',
  selectComplete: '선택 완료',
  selectSubstituteSuccess: '{name}님을 대타로 선택했습니다. 관리자에게 최종 승인을 요청하세요.',
  processErrorMsg: '처리 중 문제가 발생했습니다.',
  select: '선택',
  applicantsList: '지원자 목록',
  noApplicantsYet: '아직 지원자가 없습니다.',
  permissionRequired: '권한 필요',
  galleryPermissionRequired: '갤러리 접근 권한이 필요합니다.',
  uploadComplete: '업로드 완료',
  healthCertUploadedMsg: '보건증이 업로드되었으며, 관리자 승인 대기 중입니다.',
  uploadErrorMsg: '업로드 중 문제가 발생했습니다.',
  pendingApprovalMsg: '⏳ 관리자가 확인하고 있으며, 승인 후 만료일이 표시됩니다.',
  rejectedApprovalMsg: '❌ 서류가 반려되었습니다. 다시 올바른 이미지를 업로드해주세요.',
  healthCertExpiredMsg: '⚠️ 보건증 유효기간이 만료되었습니다. 갱신 후 재업로드 해주세요.',
  healthCertRenewalNotice: '⚠️ 보건증 갱신 기한이 30일 이내로 다가왔습니다.',
  noHealthCertsRegistered: '등록된 보건증이 없습니다.',
  sendToServer: '서버로 전송',
  uploadDescription: '터치하여 갤러리에서 선택하거나 새로 촬영하세요',
  ocrDisclaimer: '※ 업로드된 이미지는 AI(OCR)를 통해 갱신일이 자동 인식됩니다.',
  sendComplete: '전송 완료',
  contractUploadedMsg: '계약서가 업로드되었습니다. 점주 승인 후 최종 반영됩니다.',
  renewContractTitle: '계약서 갱신 / 새로 업로드',
  renewContractDesc: '새로 서명한 근로계약서가 있다면 업로드해주세요',
  pendingApprovalTitle: '점주 승인 대기 중',
  pendingApprovalDesc: '제출하신 계약서의 확인이 진행 중입니다.',
  rejectedContractTitle: '계약서 반려됨 / 재업로드',
  rejectedContractDesc: '서명에 오류가 있습니다. 다시 선명하게 촬영하여 업로드해주세요',
  uploadContractTitle: '근로계약서 업로드',
  uploadContractDesc: '작성한 근로계약서 사진을 업로드해주세요',
  unregistered: '미등록',
  unassignedBranch: '미지정 매장',
  lineLink: 'LINE 연동',
  lineLinked: 'LINE 연동 완료',
  lineUnlinked: 'LINE 미연동',
  linkLineBtn: 'LINE 계정 연동하기',
  unlinkLineBtn: 'LINE 연동 해제',
  unlinkLineConfirm: 'LINE 연동을 해제하시겠습니까?',
  lineLinkError: 'LINE 연동 상태 조회 실패',
  valid: '유효함',
  pendingApproval: '승인 대기중',
  expired: '만료됨',
  needsRenewal: '갱신 필요',
  expiryDate: '만료일',
  uploadNew: '새로운 사진 업로드',
  workPlace: '근무지',
  startDate: '시작일',
  wage: '시급',
  boardTabAll: '전체',
  boardTabNotice: '공지사항',
  boardTabMenu: '건의사항',
  boardTabEvent: '자유게시판',
  boardTabManual: '매뉴얼',
  boardTabLost: '분실물',
  boardTabChecklist: '체크리스트',
  boardTabPromotion: '프로모션/이벤트',
  boardTabWorkOrder: '업무지시',
  board: '게시판',
  addTab: '탭 추가',
  enterTabName: '탭 이름을 입력해주세요.',
  noStoreOrUserInfo: '매장 또는 사용자 정보가 없습니다.',
  failedToAddTab: '탭 추가 중 오류가 발생했습니다.',
  confirmDeleteTab: '\'{name}\' 탭을 삭제하시겠습니까?',
  failedToDeleteTab: '탭 삭제 중 오류가 발생했습니다.',
  deletePostConfirmMsg: '이 게시글을 정말 삭제하시겠습니까?',
  tabName: '탭 이름',
  tabNamePlaceholder: '예: 업무 지시',
  adding: '추가 중...',
  add: '추가',
  more: '더보기',
  substituteTitle: '대타 구하기',
  month_1: '1월',
  month_2: '2월',
  month_3: '3월',
  month_4: '4월',
  month_5: '5월',
  month_6: '6월',
  month_7: '7월',
  month_8: '8월',
  month_9: '9월',
  month_10: '10월',
  month_11: '11월',
  month_12: '12월',
  yearMonthPattern: '{year}년 {month}',
  request: '요청',
  enterReason: '사유를 입력해주세요.',
  requestSuccessTitle: '요청 완료',
  leaveRequestSuccessMsg: '휴무 요청을 전송하였습니다.',
  substituteRequestSuccessMsg: '대타 요청 상태로 표시했습니다.',
  requestFailTitle: '요청 실패',
  requestFailMsg: '잠시 후 다시 시도해주세요.',
  loadScheduleFailTitle: '스케줄 조회 실패',
  loadScheduleFailMsg: '근무표를 불러오지 못했습니다.',
  peopleUnit: '명',
  casesUnit: '건',
  noEmployee: '직원없음',
  substituteRequestsLabel: '대타 요청',
  staffLabel: '직원',
  adminLabel: '관리자',
  usernamePlaceholder: '아이디를 입력하세요',
  passwordPlaceholder: '비밀번호를 입력하세요',
  loginBtn: '로그인',
  signupBtn: '회원가입',
  inputError: '입력 오류',
  loginFieldsRequired: '아이디와 비밀번호를 모두 입력해주세요.',
  loginFailed: '로그인 실패',
  loginRoleMismatch: '선택한 로그인 유형과 계정 권한이 일치하지 않습니다.',
  loginCredentialsCheck: '아이디 또는 비밀번호를 확인해주세요.',
  signupAsStaff: '직원으로 가입',
  signupAsStaffDesc: '매장에서 근무하는 직원으로 가입을 진행합니다.',
  staffButtonDesc: '매장 스케줄에 따라 근무하는 직원입니다.',
  adminSignup: '관리자 회원가입',
  staffSignup: '직원 회원가입',
  basicInfo: '기본 정보',
  usernameLabel: '아이디',
  passwordLabel: '비밀번호',
  passwordCheckLabel: '비밀번호 확인',
  storeInfo: '매장 정보',
  categoryLabel: '업종 카테고리',
  isFranchiseLabel: '프랜차이즈 매장인가요?',
  brandNamePlaceholder: '브랜드명 (예: 컴포즈커피)',
  branchNamePlaceholder: '지점명 (예: 미금점)',
  storeAddressPlaceholder: '매장 주소',
  openTimeLabel: '오픈 시간',
  closeTimeLabel: '마감 시간',
  maxCapacityLabel: '최대 수용 인원 (선택)',
  numbersOnlyPlaceholder: '숫자만 입력',
  signingUp: '가입 처리 중...',
  signupComplete: '가입 완료',
  selectStoreCategory: '업종 선택',
  requiredFieldsMsg: '모든 필수 항목을 입력해주세요.',
  adminFieldsMsg: '브랜드명, 지점명, 주소를 모두 입력해주세요.',
  passwordError: '비밀번호 오류',
  passwordMismatchMsg: '비밀번호가 일치하지 않습니다.',
  signupSuccess: '가입 성공',
  welcomeMsg: '님 환영합니다!',
  signupFailed: '가입 실패',
  alreadyUsedInfoMsg: '이미 사용 중인 정보입니다.',
  corsErrorMsg: '요청이 차단되었습니다. 백엔드 서버를 재시작하고 CORS 설정이 적용되었는지 확인해주세요.',
  serverErrorMsg: '서버 오류: ',
  backendConnectionErrorMsg: '백엔드 서버에 연결할 수 없습니다.',
  unknownErrorMsg: '알 수 없는 오류가 발생했습니다.',
  catCafe: '카페',
  catRestaurant: '음식점',
  catFastfood: '패스트푸드',
  catClothing: '의류/잡화',
  catService: '서비스',
  catOther: '기타',
  staffListLoadFailed: '직원 목록 조회 실패',
  staffListLoadFailedMsg: '백엔드에서 직원 정보를 불러오지 못했습니다.',
  workingEmployees: '근무 중인 직원',
  pendingLabel: '대기',
  refresh: '새로고침',
  loadingStaff: '직원 정보를 불러오는 중입니다.',
  noEmployeesTitle: '직원이 없습니다.',
  noEmployeesDesc: '선택된 매장에 등록된 직원이 없습니다.',
  employeeDetailTitle: '직원 상세 정보',
  approved: '승인됨',
  noStoreInfo: '선택된 매장 정보가 없습니다.',
  approvedStaffMsg: '님의 근무 요청을 승인했습니다.',
  approvalFailed: '승인 실패',
  approvalFailedMsg: '직원 승인 처리 중 오류가 발생했습니다.',
  rejectRequest: '요청 거절',
  rejectConfirmMsg: '님의 근무 요청을 거절하시겠습니까?',
  rejectedStaffMsg: '님의 근무 요청을 거절했습니다.',
  rejectionFailed: '거절 실패',
  rejectionFailedMsg: '직원 요청 거절 중 오류가 발생했습니다.',
  cameraPermissionRequired: '출퇴근 QR 코드를 스캔하려면 카메라 권한이 필요합니다.',
  allowCameraPermission: '카메라 권한 허용하기',
  noLoginInfo: '로그인 정보가 없습니다.',
  pleaseLoginAgain: '다시 로그인해 주세요.',
  noQrToken: 'QR 토큰을 찾을 수 없습니다.',
  attendanceProcessed: '출퇴근 처리 완료',
  attendanceProcessedSuccess: '정상 처리되었습니다.',
  attendanceProcessFailed: '출퇴근 처리 실패',
  scanQrAgain: 'QR 코드를 다시 스캔해주세요.',
  processingAttendance: '출퇴근 처리 중입니다...',
  alignQrCodeInFrame: '사각형 영역 안에 QR 코드를 맞춰주세요',
};

const en: TranslationData = {
  greeting: 'Hello',
  suffixNim: '',
  todayWork: "Today's Shift",
  todayAttendance: "Today's QR Clock In/Out",
  notCheckedInYet: 'Not Checked In',
  notCheckedOutYet: 'Not Checked Out (Working)',
  viewMonthlyAttendance: 'View Monthly Attendance',
  noAttendanceToday: 'No attendance records for today.',
  scheduled: 'Scheduled',
  inProgress: 'In Progress',
  completed: 'Completed',
  substituteReq: 'Substitute Requested',
  offDay: 'Off',
  statusWorking: 'Working',
  statusCompleted: 'Completed',
  statusCheckedOut: 'Checked Out',
  statusLate: 'Late',
  statusEarlyLeave: 'Early Leave',
  statusAbsent: 'Absent',
  statusNormal: 'Normal',
  attendanceRecordSuffix: "'s Attendance Record",
  detailedRecord: 'Detailed Record',
  noAttendanceMonth: 'No attendance records for this month.',
  monthYearFormatPattern: 'MMMM yyyy',
  tabDashboard: 'Dashboard',
  tabSchedule: 'Schedule',
  tabEmployee: 'Staff',
  tabMyPage: 'My Info',
  tabHome: 'Home',
  tabScheduleStaff: 'Schedule',
  tabNotification: 'Alerts',
  weeklyHours: 'Weekly Hours',
  weeklySalary: 'Estimated Weekly Pay',
  subReqAlertTitle: 'New Substitute Request',
  subReqAlertDesc: 'A substitute is needed for Minjun Kim\'s shift.',
  applyBtn: 'Apply',
  rejectBtn: 'Reject',
  latestNotices: 'Latest Announcements',
  viewAll: 'View All',
  noNotices: 'No announcements registered.',
  qrCheckIn: 'QR Check-in',
  defaultUserName: 'User',
  admin: 'Admin',
  staff: 'Staff',
  myInfo: 'My Info',
  profileEdit: 'Edit Profile',
  contract: 'Labor Contract',
  healthCert: 'Health Certificate',
  appSettings: 'App Settings',
  themeMode: 'Theme Mode',
  languageSetting: 'Language',
  pushAlert: 'Push Notifications',
  logout: 'Log Out',
  withdrawBtn: 'Delete Account',
  withdrawConfirmTitle: 'Confirm Account Deletion',
  withdrawConfirmMsg: 'Are you sure you want to delete your account? This action cannot be undone.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  withdrawSuccessTitle: 'Account Deleted',
  withdrawSuccessMsg: 'Your account has been deleted. Thank you for using our service.',
  themeSettings: 'Theme Settings',
  langSettings: 'Language Settings',
  employeeManagement: 'Employee Management',
  monthlySchedule: 'Monthly Schedule',
  payroll: 'Payroll Calculation',
  internalBoard: 'Internal Board',
  adminDashboard: 'Admin Dashboard',
  brand: 'Brand',
  branch: 'Branch',
  currentlyWorking: 'Currently Working',
  requestProcessing: 'Process Requests',
  selectBranch: 'Select Branch',
  addNewBranch: '+ Add New Branch',
  close: 'Close',
  findSubstitute: 'Find Substitute',
  myPaystub: 'My Paystub',
  mySubstituteHistory: 'My Substitute History',
  storeManagement: 'Store Management',
  storeInfoEdit: 'Edit Store Info',
  healthCertManagement: 'Health Certs',
  contractManagement: 'Contracts',
  leaveRequestManagement: 'Leave Requests',
  lineConnect: 'Connect LINE',
  lightMode: 'Light Mode',
  darkMode: 'Dark Mode',
  systemSetting: 'System Theme',
  writer: 'Writer',
  views: 'Views',
  boardDetailTitle: 'Post Detail',
  unpin: 'Unpin',
  pin: 'Pin to Top',
  comments: 'Comments',
  noComments: 'No comments yet.',
  addCommentPlaceholder: 'Enter a comment...',
  register: 'Register',
  commentEmptyTitle: 'Comment Error',
  commentEmptyMsg: 'Please enter comment content.',
  deleteCommentConfirmTitle: 'Delete Comment',
  deleteCommentConfirmMsg: 'Are you sure you want to delete this comment?',
  deleteCommentSuccessTitle: 'Deleted',
  deleteCommentSuccessMsg: 'Comment has been deleted.',
  unknown: 'Unknown',
  checkIn: 'Clock In',
  checkOut: 'Clock Out',
  expectedDailyWage: 'Estimated Daily Wage',
  currency: ' KRW',
  noScheduleToday: 'No shifts scheduled for today.',
  notifListTitle: 'Notifications',
  markAllRead: 'Mark All Read',
  delete: 'Delete',
  weeklyDetailTitle: 'Weekly Shift Detail',
  noDetails: 'Failed to load details.',
  totalWorkDays: 'Work Days',
  daysUnit: ' Days',
  totalWorkHours: 'Total Hours',
  hoursUnit: ' Hours',
  appliedRate: 'Applied Rate',
  dailyWorkHistory: 'Daily Work History',
  noWeeklyWorkHistory: 'No work history for this week.',
  alert: 'Alert',
  titleContentRequired: 'Please enter both title and content.',
  success: 'Success',
  postEditSuccess: 'Post has been successfully updated.',
  newNotice: 'Post New Announcement',
  notice: 'Announcement',
  alertFailed: 'Notification Failed',
  pushAlertFailed: 'Failed to send push notification.',
  postCreateSuccess: 'Post has been successfully registered.',
  editPost: 'Edit Post',
  writeNewPost: 'Write New Post',
  selectCategory: 'Select Category',
  title: 'Title',
  titlePlaceholder: 'Enter title',
  content: 'Content',
  contentPlaceholder: 'Please describe the details.',
  editComplete: 'Save Changes',
  createComplete: 'Publish',
  suggestion: 'Suggestion',
  lost_found: 'Lost & Found',
  free_board: 'Free Board',
  leaveRequest: 'Leave Requested',
  requestComplete: 'Request Completed',
  payrollTitle: 'Payroll Details',
  estMonthlySalary: 'Estimated Monthly Salary',
  basePay: 'Base Pay',
  holidayPay: 'Holiday Pay',
  substituteBonus: 'Substitute Bonus',
  dailyWageDetail: 'Daily Wage Breakdown',
  calculatingPayroll: 'Calculating payroll details...',
  noWorkRecordThisMonth: 'No work records for this month.',
  requestSentToAdmin: 'Request has been sent to the manager.',
  unassigned: 'Unassigned',
  requestLeave: 'Request Leave',
  requestSubstitute: 'Request Substitute',
  monthlyView: 'Monthly View',
  newShift: 'New Shift',
  noSchedule: 'No shifts scheduled.',
  leaveReasonPlaceholder: 'Please enter the reason for leave.',
  substituteReasonPlaceholder: 'Please enter the reason for substitute request.',
  substituteApplyTitle: 'Apply for Substitute',
  substituteApplyMsg: 'Do you want to apply for this shift?',
  applySuccess: 'Application completed.',
  error: 'Error',
  errorApplySubstitute: 'An error occurred during application.',
  myRequest: 'My Requests',
  myApplication: 'My Applications',
  substituteRequests: 'Substitute Needed',
  history: 'History',
  noSubstituteRequests: 'No substitute requests posted.',
  noHistory: 'No request or application history.',
  todaySchedule: "Today's Schedule",
  morning: 'Morning',
  afternoon: 'Afternoon',
  closing: 'Closing',
  sun: 'Sun',
  mon: 'Mon',
  tue: 'Tue',
  wed: 'Wed',
  thu: 'Thu',
  fri: 'Fri',
  sat: 'Sat',
  selectEmployee: 'Please select an employee.',
  editShiftSuccess: 'Shift updated successfully.',
  addShiftSuccess: 'New shift added successfully.',
  deleteConfirmTitle: 'Confirm Delete',
  deleteConfirmMsg: 'Are you sure you want to delete this shift?',
  deleteShiftSuccess: 'Shift deleted successfully.',
  editShift: 'Edit Shift',
  addShift: 'Add Shift',
  selectEmployeePlaceholder: 'Select employee...',
  date: 'Date',
  startTime: 'Start Time',
  endTime: 'End Time',
  save: 'Save',
  approveRequestTitle: 'Approve Request',
  approveRequestMsg: 'Do you want to approve this request?',
  approve: 'Approve',
  approvalComplete: 'Approval Completed',
  denyRequestTitle: 'Reject Request',
  denyRequestMsg: 'Do you want to reject this request?',
  deny: 'Reject',
  denialComplete: 'Rejection Completed',
  leave: 'Leave',
  substitute: 'Substitute',
  employee: 'Employee',
  workTime: 'Work Hours',
  reason: 'Reason',
  requestManagement: 'Request Management',
  noRequests: 'No requests to process.',
  badgeNew: 'New',
  badgeImportant: 'Important',
  saveCompleteTitle: 'Saved Successfully',
  saveCompleteMsg: 'Profile has been successfully updated.',
  editFailTitle: 'Save Failed',
  editFailMsg: 'An error occurred while updating profile.',
  accountInfoReadonly: 'Account Info (Read-only)',
  idLabel: 'ID',
  branchLabel: 'Branch',
  roleLabel: 'Role',
  adminRole: 'Admin',
  staffRole: 'Staff',
  myInfoSection: 'Edit Profile',
  nameLabel: 'Name',
  namePlaceholder: 'Enter name',
  phoneLabel: 'Phone',
  phonePlaceholder: 'Enter phone number',
  changePasswordSection: 'Change Password',
  currentPasswordLabel: 'Current Password',
  currentPasswordPlaceholder: 'Enter current password',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'Enter new password',
  editCompleteBtn: 'Update Profile',
  subReqConfirmTitle: 'Confirm Application',
  subReqConfirmMsg: 'Do you want to apply for this substitute shift?',
  subApplySuccessTitle: 'Applied',
  subApplySuccessMsg: 'Substitute application completed successfully.',
  subPointUnit: 'P',
  subPointTotal: 'Total Points',
  subEmptyReq: 'No substitute requests registered.',
  subEmptyHist: 'No substitute history.',
  subTabRequest: 'Sub Requests',
  subTabHistory: 'Matching History',
  loadSubstituteFail: 'Failed to load substitute info',
  checkServerConnection: 'Please check your server connection.',
  applyFail: 'Application Failed',
  applyFailDetail: 'You have already applied or a server error occurred.',
  substituteApplyDefaultMsg: 'Applying for substitute.',
  substituteRoleDefault: 'Substitute Shift',
  dateFormatPattern: 'MMM d (eee)',
  dateFormatMD: 'MMM d',
  loadDataFail: 'Failed to load data.',
  appliedToPost: 'Applied to {id}',
  loadApplicantsFail: 'Failed to load applicants.',
  selectSubstitute: 'Select Substitute',
  selectSubstituteConfirm: 'Do you want to select {name} as the substitute? Admin\'s final approval is required.',
  selectComplete: 'Selection Complete',
  selectSubstituteSuccess: '{name} selected as substitute. Please request final approval from the admin.',
  processErrorMsg: 'An error occurred during processing.',
  select: 'Select',
  applicantsList: 'Applicants List',
  noApplicantsYet: 'No applicants yet.',
  permissionRequired: 'Permission Required',
  galleryPermissionRequired: 'Gallery access permission is required.',
  uploadComplete: 'Upload Complete',
  healthCertUploadedMsg: 'The health certificate has been uploaded and is pending admin approval.',
  uploadErrorMsg: 'A problem occurred during upload.',
  pendingApprovalMsg: '⏳ Under review by administrator. Expiration date will be shown after approval.',
  rejectedApprovalMsg: '❌ Document rejected. Please upload the correct image again.',
  healthCertExpiredMsg: '⚠️ Health certificate expired. Please renew and re-upload.',
  healthCertRenewalNotice: '⚠️ Health certificate renewal is due within 30 days.',
  noHealthCertsRegistered: 'No health certificates registered.',
  sendToServer: 'Submit to Server',
  uploadDescription: 'Touch to select from gallery or take a new photo',
  ocrDisclaimer: '* Uploaded images will have their renewal dates automatically recognized via AI (OCR).',
  sendComplete: 'Upload Successful',
  contractUploadedMsg: 'The contract has been uploaded. It will be finalized after manager approval.',
  renewContractTitle: 'Renew Contract / Upload New',
  renewContractDesc: 'Please upload if you have a newly signed contract',
  pendingApprovalTitle: 'Pending Owner Approval',
  pendingApprovalDesc: 'We are currently verifying your submitted contract.',
  rejectedContractTitle: 'Contract Rejected / Re-upload',
  rejectedContractDesc: 'Error in signature. Please take a clear photo and upload again.',
  uploadContractTitle: 'Upload Labor Contract',
  uploadContractDesc: 'Please upload a photo of the completed contract.',
  unregistered: 'Unregistered',
  unassignedBranch: 'Unassigned Branch',
  lineLink: 'LINE Link',
  lineLinked: 'LINE Linked',
  lineUnlinked: 'LINE Not Linked',
  linkLineBtn: 'Link LINE Account',
  unlinkLineBtn: 'Unlink LINE Account',
  unlinkLineConfirm: 'Are you sure you want to unlink LINE?',
  lineLinkError: 'Failed to query LINE link status',
  valid: 'Valid',
  pendingApproval: 'Pending Approval',
  expired: 'Expired',
  needsRenewal: 'Needs Renewal',
  expiryDate: 'Expiry Date',
  uploadNew: 'Upload New Photo',
  workPlace: 'Work Place',
  startDate: 'Start Date',
  wage: 'Wage',
  boardTabAll: 'All',
  boardTabNotice: 'Notices',
  boardTabMenu: 'Suggestions',
  boardTabEvent: 'Free Board',
  boardTabManual: 'Manuals',
  boardTabLost: 'Lost & Found',
  boardTabChecklist: 'Checklist',
  boardTabPromotion: 'Promotions/Events',
  boardTabWorkOrder: 'Work Orders',
  board: 'Board',
  addTab: 'Add Tab',
  enterTabName: 'Please enter a tab name.',
  noStoreOrUserInfo: 'Store or user information is missing.',
  failedToAddTab: 'An error occurred while adding the tab.',
  confirmDeleteTab: 'Are you sure you want to delete the \'{name}\' tab?',
  failedToDeleteTab: 'An error occurred while deleting the tab.',
  deletePostConfirmMsg: 'Are you sure you want to delete this post?',
  tabName: 'Tab Name',
  tabNamePlaceholder: 'e.g. Work Orders',
  adding: 'Adding...',
  add: 'Add',
  more: 'More',
  substituteTitle: 'Find Substitutes',
  month_1: 'January',
  month_2: 'February',
  month_3: 'March',
  month_4: 'April',
  month_5: 'May',
  month_6: 'June',
  month_7: 'July',
  month_8: 'August',
  month_9: 'September',
  month_10: 'October',
  month_11: 'November',
  month_12: 'December',
  yearMonthPattern: '{month} {year}',
  request: 'Request',
  enterReason: 'Please enter the reason.',
  requestSuccessTitle: 'Request Completed',
  leaveRequestSuccessMsg: 'Leave request has been sent.',
  substituteRequestSuccessMsg: 'Marked as substitute requested.',
  requestFailTitle: 'Request Failed',
  requestFailMsg: 'Please try again in a moment.',
  loadScheduleFailTitle: 'Failed to load schedule',
  loadScheduleFailMsg: 'Could not load the work schedule.',
  peopleUnit: ' people',
  casesUnit: ' cases',
  noEmployee: 'No Staff',
  substituteRequestsLabel: 'Sub Requests',
  staffLabel: 'Staff',
  adminLabel: 'Admin',
  usernamePlaceholder: 'Enter ID',
  passwordPlaceholder: 'Enter Password',
  loginBtn: 'Log In',
  signupBtn: 'Sign Up',
  inputError: 'Input Error',
  loginFieldsRequired: 'Please enter both ID and password.',
  loginFailed: 'Login Failed',
  loginRoleMismatch: 'The selected login type does not match your account permissions.',
  loginCredentialsCheck: 'Please check your ID or password.',
  signupAsStaff: 'Sign Up as Staff',
  signupAsStaffDesc: 'Proceed with signing up as a staff member working at a store.',
  staffButtonDesc: 'A staff member working according to the store schedule.',
  adminSignup: 'Admin Sign Up',
  staffSignup: 'Staff Sign Up',
  basicInfo: 'Basic Information',
  usernameLabel: 'ID',
  passwordLabel: 'Password',
  passwordCheckLabel: 'Confirm Password',
  storeInfo: 'Store Information',
  categoryLabel: 'Category',
  isFranchiseLabel: 'Is it a franchise store?',
  brandNamePlaceholder: 'Brand Name (e.g. Compose Coffee)',
  branchNamePlaceholder: 'Branch Name (e.g. Migeum)',
  storeAddressPlaceholder: 'Store Address',
  openTimeLabel: 'Open Time',
  closeTimeLabel: 'Close Time',
  maxCapacityLabel: 'Max Capacity (Optional)',
  numbersOnlyPlaceholder: 'Numbers only',
  signingUp: 'Signing up...',
  signupComplete: 'Sign Up Complete',
  selectStoreCategory: 'Select Category',
  requiredFieldsMsg: 'Please fill in all required fields.',
  adminFieldsMsg: 'Please enter brand name, branch name, and address.',
  passwordError: 'Password Error',
  passwordMismatchMsg: 'Passwords do not match.',
  signupSuccess: 'Sign Up Success',
  welcomeMsg: ', Welcome!',
  signupFailed: 'Sign Up Failed',
  alreadyUsedInfoMsg: 'This information is already in use.',
  corsErrorMsg: 'Request blocked. Please restart backend and check CORS settings.',
  serverErrorMsg: 'Server Error: ',
  backendConnectionErrorMsg: 'Cannot connect to backend server.',
  unknownErrorMsg: 'An unknown error has occurred.',
  catCafe: 'Cafe',
  catRestaurant: 'Restaurant',
  catFastfood: 'Fast Food',
  catClothing: 'Clothing/Goods',
  catService: 'Service',
  catOther: 'Other',
  staffListLoadFailed: 'Failed to retrieve employee list',
  staffListLoadFailedMsg: 'Failed to load employee details from server.',
  workingEmployees: 'Working Staff',
  pendingLabel: 'Pending',
  refresh: 'Refresh',
  loadingStaff: 'Loading employee information...',
  noEmployeesTitle: 'No employees found.',
  noEmployeesDesc: 'There are no employees registered in the selected branch.',
  employeeDetailTitle: 'Employee Details',
  approved: 'Approved',
  noStoreInfo: 'No store information selected.',
  approvedStaffMsg: '\'s request approved.',
  approvalFailed: 'Approval Failed',
  approvalFailedMsg: 'An error occurred during employee approval.',
  rejectRequest: 'Reject Request',
  rejectConfirmMsg: 'Are you sure you want to reject this request?',
  rejectedStaffMsg: '\'s request declined.',
  rejectionFailed: 'Rejection Failed',
  rejectionFailedMsg: 'An error occurred while rejecting the employee request.',
  cameraPermissionRequired: 'Camera permission is required to scan the attendance QR code.',
  allowCameraPermission: 'Allow Camera Permission',
  noLoginInfo: 'No login information found.',
  pleaseLoginAgain: 'Please log in again.',
  noQrToken: 'QR token not found.',
  attendanceProcessed: 'Attendance process complete',
  attendanceProcessedSuccess: 'Successfully processed.',
  attendanceProcessFailed: 'Attendance process failed',
  scanQrAgain: 'Please scan the QR code again.',
  processingAttendance: 'Processing attendance...',
  alignQrCodeInFrame: 'Align the QR code inside the frame',
};

const ja: TranslationData = {
  greeting: 'こんにちは',
  suffixNim: '様',
  todayWork: '今日の勤務',
  todayAttendance: '今日の出退勤記録',
  notCheckedInYet: '出勤前',
  notCheckedOutYet: '退勤前 (勤務中)',
  viewMonthlyAttendance: '月間出退勤履歴を見る',
  noAttendanceToday: '今日の出退勤記録がありません。',
  scheduled: '勤務予定',
  inProgress: '勤務中',
  completed: '勤務完了',
  substituteReq: '代打要請中',
  offDay: '休み',
  statusWorking: '勤務中',
  statusCompleted: '勤務完了',
  statusCheckedOut: '退勤完了',
  statusLate: '遅刻',
  statusEarlyLeave: '早退',
  statusAbsent: '欠勤',
  statusNormal: '正常',
  attendanceRecordSuffix: '様の出退勤記録',
  detailedRecord: '詳細履歴',
  noAttendanceMonth: '該当月の出退勤記録がありません。',
  monthYearFormatPattern: 'yyyy年 M月',
  tabDashboard: 'ダッシュボード',
  tabSchedule: 'シフト管理',
  tabEmployee: '従業員管理',
  tabMyPage: 'マイページ',
  tabHome: 'ホーム',
  tabScheduleStaff: 'スケジュール',
  tabNotification: '通知',
  weeklyHours: '今週の勤務時間',
  weeklySalary: '今週の予想給与',
  subReqAlertTitle: '新しい代打要請',
  subReqAlertDesc: 'キム・ミンジュン様の勤務に代打応募が必要です。',
  applyBtn: '応募する',
  rejectBtn: '拒否',
  latestNotices: '最新のお知らせ',
  viewAll: 'すべて見る',
  noNotices: '登録されたお知らせがありません。',
  qrCheckIn: 'QRチェックイン',
  defaultUserName: 'ユーザー',
  admin: '管理者',
  staff: 'スタッフ',
  myInfo: 'マイページ',
  profileEdit: 'プロフィール編集',
  contract: '雇用契約書',
  healthCert: '検便・健康診断証',
  appSettings: 'アプリ設定',
  themeMode: 'テーマモード',
  languageSetting: '言語設定',
  pushAlert: 'プッシュ通知',
  logout: 'ログアウト',
  withdrawBtn: '退会する',
  withdrawConfirmTitle: '退会確認',
  withdrawConfirmMsg: '本当に退会しますか？この操作は取り消せません。',
  cancel: 'キャンセル',
  confirm: '確認',
  withdrawSuccessTitle: '退会完了',
  withdrawSuccessMsg: '退会が完了しました。ご利用いただきありがとうございました。',
  themeSettings: 'テーマ設定',
  langSettings: '言語設定',
  employeeManagement: '従業員管理',
  monthlySchedule: '月間シフト表',
  payroll: '給与計算',
  internalBoard: '社내掲示板',
  adminDashboard: '管理者ダッシュボード',
  brand: 'ブランド',
  branch: '店舗',
  currentlyWorking: '現在勤務中',
  requestProcessing: '申請処理',
  selectBranch: '店舗選択',
  addNewBranch: '+ 新規店舗追加',
  close: '閉じる',
  findSubstitute: '代打を探す',
  myPaystub: '給与明細書',
  mySubstituteHistory: '自分の代打履歴',
  storeManagement: '店舗管理',
  storeInfoEdit: '店舗情報修正',
  healthCertManagement: '健康診断証管理',
  contractManagement: '契約書管理',
  leaveRequestManagement: '休暇申請管理',
  lineConnect: 'LINE連携',
  lightMode: 'ライトモード',
  darkMode: 'ダークモード',
  systemSetting: 'システム設定',
  writer: '作成者',
  views: '閲覧数',
  boardDetailTitle: '投稿詳細',
  unpin: 'ピン留め解除',
  pin: 'ピン留め',
  comments: 'コメント',
  noComments: 'コメントはまだありません。',
  addCommentPlaceholder: 'コメントを入力してください...',
  register: '登録',
  commentEmptyTitle: 'コメントエラー',
  commentEmptyMsg: 'コメント内容を入力してください。',
  deleteCommentConfirmTitle: 'コメント削除',
  deleteCommentConfirmMsg: 'このコメントを本当に削除しますか？',
  deleteCommentSuccessTitle: '削除完了',
  deleteCommentSuccessMsg: 'コメントが削除されました。',
  unknown: '不明',
  checkIn: '出勤',
  checkOut: '退勤',
  expectedDailyWage: '予想日給',
  currency: ' ウォン',
  noScheduleToday: '本日の予定シフトはありません。',
  notifListTitle: '通知一覧',
  markAllRead: 'すべて既読にする',
  delete: '削除',
  weeklyDetailTitle: '週間勤務詳細',
  noDetails: '詳細履歴を読み込めませんでした。',
  totalWorkDays: '勤務日数',
  daysUnit: '日',
  totalWorkHours: '総時間',
  hoursUnit: '時間',
  appliedRate: '適用時給',
  dailyWorkHistory: '日別勤務内訳',
  noWeeklyWorkHistory: '今週の勤務記録がありません。',
  alert: '通知',
  titleContentRequired: 'タイトルと内容の両方を入力してください。',
  success: '成功',
  postEditSuccess: '投稿が正常に修正されました。',
  newNotice: '新規お知らせ登録',
  notice: 'お知らせ',
  alertFailed: '通知失敗',
  pushAlertFailed: 'プッシュ通知の送信に失敗しました。',
  postCreateSuccess: '投稿が正常に登録されました。',
  editPost: '投稿編集',
  writeNewPost: '新規投稿',
  selectCategory: 'カテゴリー選択',
  title: 'タイトル',
  titlePlaceholder: 'タイトルを入力してください',
  content: '内容',
  contentPlaceholder: '内容を詳しく記入してください。',
  editComplete: '修正する',
  createComplete: '登録する',
  suggestion: 'ご意見・提案',
  lost_found: '忘れ物',
  free_board: '自由掲示板',
  leaveRequest: '休暇申請保留中',
  requestComplete: '申請完了',
  payrollTitle: '給与計算詳細',
  estMonthlySalary: '今月の予想給与',
  basePay: '基本給',
  holidayPay: '週休手当',
  substituteBonus: '代打手当',
  dailyWageDetail: '日別給与内訳',
  calculatingPayroll: '給与内訳を計算中です...',
  noWorkRecordThisMonth: '今月の勤務記録がありません。',
  requestSentToAdmin: '店舗管理者に申請が送信されました。',
  unassigned: '未割り当て',
  requestLeave: '休暇申請',
  requestSubstitute: '代打申請',
  monthlyView: '月間表示',
  newShift: '新規シフト',
  noSchedule: '予定されたシフトはありません。',
  leaveReasonPlaceholder: '休暇の理由を入力してください。',
  substituteReasonPlaceholder: '代打要請の理由を入力してください。',
  substituteApplyTitle: '代打応募',
  substituteApplyMsg: 'このシフトに代打として応募しますか？',
  applySuccess: '応募が完了しました。',
  error: 'エラー',
  errorApplySubstitute: '応募中にエラーが発生しました。',
  myRequest: '自分が作成した要請',
  myApplication: '自分が応募した要請',
  substituteRequests: '代打募集',
  history: '履歴',
  noSubstituteRequests: '現在募集中の代打はありません。',
  noHistory: '要請または応募の履歴がありません。',
  todaySchedule: '今日のスケジュール',
  morning: '午前',
  afternoon: '午後',
  closing: '締め',
  sun: '日',
  mon: '月',
  tue: '火',
  wed: '水',
  thu: '木',
  fri: '金',
  sat: '土',
  selectEmployee: '従業員を選択してください。',
  editShiftSuccess: 'シフトの更新が完了しました。',
  addShiftSuccess: '新規シフトの追加が完了しました。',
  deleteConfirmTitle: '削除の確認',
  deleteConfirmMsg: 'このシフトを本当に削除しますか？',
  deleteShiftSuccess: 'シフトが削除されました。',
  editShift: 'シフト編集',
  addShift: '新規シフト追加',
  selectEmployeePlaceholder: '従業員を選択してください...',
  date: '日付',
  startTime: '開始時間',
  endTime: '終了時間',
  save: '保存',
  approveRequestTitle: '申請承認',
  approveRequestMsg: 'この申請を承認しますか？',
  approve: '承認',
  approvalComplete: '承認が完了しました。',
  denyRequestTitle: '申請拒否',
  denyRequestMsg: 'この申請を拒否しますか？',
  deny: '拒否',
  denialComplete: '拒否処理が完了しました。',
  leave: '休暇',
  substitute: '代打',
  employee: '従業員',
  workTime: '勤務時間',
  reason: '理由',
  requestManagement: '申請管理',
  noRequests: '処理する申請はありません。',
  badgeNew: '新規',
  badgeImportant: '重要',
  saveCompleteTitle: '保存完了',
  saveCompleteMsg: '個人情報が正常に修正されました。',
  editFailTitle: '修正失敗',
  editFailMsg: '個人情報の修正中にエラーが発生しました。',
  accountInfoReadonly: 'アカウント情報（編集不可）',
  idLabel: 'ユーザーID',
  branchLabel: '勤務店舗',
  roleLabel: '権限',
  adminRole: '管理者',
  staffRole: 'スタッフ',
  myInfoSection: 'プロフィール編集',
  nameLabel: 'お名前',
  namePlaceholder: 'お名前を入力してください',
  phoneLabel: '電話番号',
  phonePlaceholder: '電話番号を入力してください',
  changePasswordSection: 'パスワード変更',
  currentPasswordLabel: '現在のパスワード',
  currentPasswordPlaceholder: '現在のパスワードを入力',
  newPasswordLabel: '新しいパスワード',
  newPasswordPlaceholder: '新しいパスワードを入力',
  editCompleteBtn: 'プロフィール更新',
  subReqConfirmTitle: '応募確認',
  subReqConfirmMsg: 'このシフトに代打応募しますか？',
  subApplySuccessTitle: '応募完了',
  subApplySuccessMsg: '代打応募が正常に完了しました。',
  subPointUnit: 'P',
  subPointTotal: '累計ポイント',
  subEmptyReq: '登録された代打要請はありません。',
  subEmptyHist: '代打履歴が存在しません。',
  subTabRequest: '代打要請',
  subTabHistory: 'マッチング履歴',
  loadSubstituteFail: '代打情報の読み込みに失敗しました',
  checkServerConnection: 'サーバーの接続状態を確認してください。',
  applyFail: '応募失敗',
  applyFailDetail: '既に応募しているか、サーバーエラーが発生しました。',
  substituteApplyDefaultMsg: '代打に応募します。',
  substituteRoleDefault: '代打勤務',
  dateFormatPattern: 'M月d日 (eee)',
  dateFormatMD: 'M月d日',
  loadDataFail: 'データの取得に失敗しました。',
  appliedToPost: '{id}に応募しました',
  loadApplicantsFail: '応募者一覧の取得に失敗しました。',
  selectSubstitute: '代打選択',
  selectSubstituteConfirm: '{name}様を代打勤務者として選択しますか？管理者の最終承認が必要です。',
  selectComplete: '選択完了',
  selectSubstituteSuccess: '{name}様를代打として選択しました。管理者に最終承認を要請してください。',
  processErrorMsg: '処理中にエラーが発生しました。',
  select: '選択',
  applicantsList: '応募者一覧',
  noApplicantsYet: '応募者はまだいません。',
  permissionRequired: '権限が必要',
  galleryPermissionRequired: 'ギャラリーへのアクセス権限が必要です。',
  uploadComplete: 'アップロード完了',
  healthCertUploadedMsg: '保健所証がアップロードされ、管理者の承認待ちです。',
  uploadErrorMsg: 'アップロード中に問題が発生しました。',
  pendingApprovalMsg: '⏳ 管理者が確認中です。承認後に有効期限が表示されます。',
  rejectedApprovalMsg: '❌ 書類が却下されました。再度正しい画像をアップロードしてください。',
  healthCertExpiredMsg: '⚠️ 保健所証の有効期限が切れました。更新して再アップロードしてください。',
  healthCertRenewalNotice: '⚠️ 保健所証の更新期限が30日以内に近づいています。',
  noHealthCertsRegistered: '登録された保健所証がありません。',
  sendToServer: 'サーバーへ送信',
  uploadDescription: 'タップしてギャラリーから選択するか、新しく撮影してください',
  ocrDisclaimer: '※ アップロードされた画像は、AI(OCR)を通じて更新日が自動認識されます。',
  sendComplete: '送信完了',
  contractUploadedMsg: '契約書がアップロードされました。管理者の承認後に最終反映されます。',
  renewContractTitle: '契約の更新 / 新規アップロード',
  renewContractDesc: '新しく署名した雇用契約書があればアップロードしてください',
  pendingApprovalTitle: '雇用主の承認待ち',
  pendingApprovalDesc: '提出された契約書の確認が行われています。',
  rejectedContractTitle: '契約書却下 / 再アップロード',
  rejectedContractDesc: '署名に誤りがあります。再度鮮明に撮影してアップロードしてください',
  uploadContractTitle: '雇用契約書のアップロード',
  uploadContractDesc: '作成した雇用契約書の写真をアップロードしてください',
  unregistered: '未登録',
  unassignedBranch: '未指定店舗',
  lineLink: 'LINE連動',
  lineLinked: 'LINE連動済み', // wait, let's write LINE連動済み
  lineUnlinked: 'LINE未連動',
  linkLineBtn: 'LINEアカウントを連動する',
  unlinkLineBtn: 'LINE連動解除',
  unlinkLineConfirm: 'LINEの連動を解除しますか？',
  lineLinkError: 'LINE連動状態の取得に失敗しました',
  valid: '有効',
  pendingApproval: '承認待ち',
  expired: '期限切れ',
  needsRenewal: '更新が必要',
  expiryDate: '有効期限',
  uploadNew: '写真をアップロード',
  workPlace: '勤務地',
  startDate: '開始日',
  wage: '時給',
  boardTabAll: 'すべて',
  boardTabNotice: 'お知らせ',
  boardTabMenu: 'ご意見箱',
  boardTabEvent: '自由掲示板',
  boardTabManual: 'マニュアル',
  boardTabLost: '忘れ物',
  boardTabChecklist: 'チェックリスト',
  boardTabPromotion: 'プロモーション/イベント',
  boardTabWorkOrder: '業務指示',
  board: '掲示板',
  addTab: 'タブ追加',
  enterTabName: 'タブ名を入力してください。',
  noStoreOrUserInfo: '店舗またはユーザー情報がありません。',
  failedToAddTab: 'タブ追加中にエラーが発生しました。',
  confirmDeleteTab: '\'{name}\' タブを削除しますか？',
  failedToDeleteTab: 'タブ削除中にエラーが発生しました。',
  deletePostConfirmMsg: 'この投稿を本当に削除しますか？',
  tabName: 'タブ名',
  tabNamePlaceholder: '例: 業務指示',
  adding: '追加中...',
  add: '追加',
  more: 'もっと見る',
  substituteTitle: '代打を探す',
  month_1: '1月',
  month_2: '2月',
  month_3: '3月',
  month_4: '4月',
  month_5: '5月',
  month_6: '6月',
  month_7: '7月',
  month_8: '8月',
  month_9: '9月',
  month_10: '10月',
  month_11: '11月',
  month_12: '12月',
  yearMonthPattern: '{year}年 {month}',
  request: '要請',
  enterReason: '理由を入力してください。',
  requestSuccessTitle: '申請完了',
  leaveRequestSuccessMsg: '休暇申請を送信しました。',
  substituteRequestSuccessMsg: '代打要請状態に設定しました。',
  requestFailTitle: '申請失敗',
  requestFailMsg: 'しばらくしてからもう一度お試しください。',
  loadScheduleFailTitle: 'シフト照会失敗',
  loadScheduleFailMsg: 'シフト表を読み込めませんでした。',
  peopleUnit: '人',
  casesUnit: '件',
  noEmployee: 'スタッフなし',
  substituteRequestsLabel: '代打要請',
  staffLabel: 'スタッフ',
  adminLabel: '管理者',
  usernamePlaceholder: 'ユーザーIDを入力してください',
  passwordPlaceholder: 'パスワードを入力してください',
  loginBtn: 'ログイン',
  signupBtn: '会員登録',
  inputError: '入力エラー',
  loginFieldsRequired: 'ユーザーIDとパスワードを両方入力してください。',
  loginFailed: 'ログイン失敗',
  loginRoleMismatch: '選択したログインタイプとアカウント権限が一致しません。',
  loginCredentialsCheck: 'ユーザーIDまたはパスワードを確認してください。',
  signupAsStaff: 'スタッフとして登録',
  signupAsStaffDesc: '店舗で勤務するスタッフとして登録を進めます。',
  staffButtonDesc: '店舗スケジュールに従って勤務するスタッフです。',
  adminSignup: '管理者会員登録',
  staffSignup: 'スタッフ会員登録',
  basicInfo: '基本情報',
  usernameLabel: 'ユーザーID',
  passwordLabel: 'パスワード',
  passwordCheckLabel: 'パスワード確認',
  storeInfo: '店舗情報',
  categoryLabel: '業種カテゴリー',
  isFranchiseLabel: 'フランチャイズ店舗ですか？',
  brandNamePlaceholder: 'ブランド名 (例: スターバックス)',
  branchNamePlaceholder: '店舗名 (例: 渋谷店)',
  storeAddressPlaceholder: '店舗住所',
  openTimeLabel: 'オープン時間',
  closeTimeLabel: 'クローズ時間',
  maxCapacityLabel: '最大収容人数 (任意)',
  numbersOnlyPlaceholder: '数字のみ入力',
  signingUp: '登録処理중...',
  signupComplete: '登録完了',
  selectStoreCategory: '業種選択',
  requiredFieldsMsg: 'すべての必須項目を入力してください。',
  adminFieldsMsg: 'ブランド名、店舗名、住所をすべて入力してください。',
  passwordError: 'パスワードエラー',
  passwordMismatchMsg: 'パスワードが一致しません。',
  signupSuccess: '登録成功',
  welcomeMsg: '様、歓迎します！',
  signupFailed: '登録失敗',
  alreadyUsedInfoMsg: 'すでに使用されている情報です。',
  corsErrorMsg: 'リクエストがブロックされました。バックエンドサーバーを再起動し、CORS設定が適用されているか確認してください。',
  serverErrorMsg: 'サーバーエラー: ',
  backendConnectionErrorMsg: 'バックエンドサーバーに接続できません。',
  unknownErrorMsg: '不明なエラーが発生しました。',
  catCafe: 'カフェ',
  catRestaurant: '飲食店',
  catFastfood: 'ファストフード',
  catClothing: '衣類・雑貨',
  catService: 'サービス',
  catOther: 'その他',
  staffListLoadFailed: '従業員リストの取得に失敗しました',
  staffListLoadFailedMsg: 'バックエンドから従業員情報を読み込めませんでした。',
  workingEmployees: '勤務中の従業員',
  pendingLabel: '待機',
  refresh: '更新',
  loadingStaff: '従業員情報を読み込んでいます。',
  noEmployeesTitle: '従業員がいません。',
  noEmployeesDesc: '選択された店舗に登録された従業員がいません。',
  employeeDetailTitle: '従業員詳細情報',
  approved: '承認済み',
  noStoreInfo: '選択された店舗情報がありません。',
  approvedStaffMsg: '様の勤務申請を承認しました。',
  approvalFailed: '承認失敗',
  approvalFailedMsg: '従業員の承認処理中にエラーが発生しました。',
  rejectRequest: '申請拒否',
  rejectConfirmMsg: '様の勤務申請を拒否しますか？',
  rejectedStaffMsg: '様の勤務申請を拒否しました。',
  rejectionFailed: '拒否失敗',
  rejectionFailedMsg: '従業員申請の拒否中にエラーが発生しました。',
  cameraPermissionRequired: '出退勤QRコードをスキャンするにはカメラの権限が必要です。',
  allowCameraPermission: 'カメラ権限を許可する',
  noLoginInfo: 'ログイン情報がありません。',
  pleaseLoginAgain: '再度ログインしてください。',
  noQrToken: 'QRトークンが見つかりません。',
  attendanceProcessed: '出退勤処理完了',
  attendanceProcessedSuccess: '正常に処理されました。',
  attendanceProcessFailed: '出退勤処理失敗',
  scanQrAgain: 'QRコードを再度スキャンしてください。',
  processingAttendance: '出退勤処理中です...',
  alignQrCodeInFrame: '四角い枠内にQRコードを合わせてください',
};

export type Language = '한국어' | 'English' | '日本語';
type TranslationData = typeof ko;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof TranslationData | string) => string;
  isTranslating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('한국어');
  const translations: { [key: string]: TranslationData } = { ko, en, ja };

  useEffect(() => {
    const loadLanguage = async () => {
      const savedLang = await AsyncStorage.getItem('language') as Language | null;
      if (savedLang) {
        setLanguageState(savedLang);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    if (lang === language) return;
    setLanguageState(lang);
    await AsyncStorage.setItem('language', lang);
  };

  const t = (key: keyof TranslationData | string): string => {
    const langCode = language === 'English' ? 'en' : language === '日本語' ? 'ja' : 'ko';
    const translationSet = translations[langCode] || translations.ko;
    return (translationSet as any)[key] || (translations.ko as any)[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTranslating: false }}>
      {children}
    </LanguageContext.Provider>
  );
};
