import React, { createContext, useState, useContext } from 'react';

export type Language = '한국어' | 'English' | '日本語';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// 다국어 사전 (필요한 텍스트를 여기에 계속 추가하면 됩니다)
const translations = {
  '한국어': {
    greeting: '안녕하세요',
    admin: '관리자',
    staff: '일반 직원',
    todayWork: '오늘의 근무',
    weeklyHours: '이번 주 근무 시간',
    weeklySalary: '이번 주 예상급여',
    notice: '사내 게시판',
    more: '더보기',
    myInfo: '내 정보 관리',
    profileEdit: '개인정보 수정',
    contract: '나의 근로계약서',
    healthCert: '보건증 관리',
    appSettings: '앱 설정',
    themeMode: '화면 모드',
    languageSetting: '언어 설정',
    pushAlert: '앱 푸시 알림',
    logout: '로그아웃',
    scheduled: '근무 예정',
    inProgress: '근무 중',
    completed: '근무 완료',
    substituteReq: '대타 찾는 중',
    offDay: '휴무',
    leaveRequest: '휴무 신청 / 대타 구하기',
    noSchedule: '선택한 날짜에는 근무 일정이 없습니다.',
    leaveReasonPlaceholder: '휴무 사유를 상세히 적어주세요 (예: 병원 진료, 학교 시험 등)',
    cancel: '취소',
    apply: '신청하기',
    monthlyView: '월간 보기',
    close: '닫기',
    sun: '일',
    mon: '월',
    tue: '화',
    wed: '수',
    thu: '목',
    fri: '금',
    sat: '토',
    month: '월',
    year: '년',
    // 모달 및 탭 텍스트
    themeSettings: '화면 모드 설정',
    themeLight: '라이트 모드',
    themeDark: '다크 모드',
    themeSystem: '시스템 설정',
    langSettings: '언어 설정',
    tabHome: '홈',
    tabSchedule: '내 스케줄',
    tabNotif: '알림',
    tabMyPage: '마이페이지',
    tabAdminHome: '매장 관리',
    tabAdminSchedule: '스케줄 관리',
    tabAdminSettings: '설정',
    // 알림 더미데이터 텍스트
    notifSubReqTitle: '🚨 대타 요청 알림',
    notifSubReqMsg: '5월 28일 수요일 17:00~22:00 대타 요청이 있습니다. 앱에서 확인 후 지원해주세요!',
    notifNoticeTitle: '📢 [공지] 가을 시즌 신메뉴 출시',
    notifNoticeMsg: '가을 시즌 신메뉴가 곧 출시됩니다!\n\n게시판에서 레시피 및 상세 매뉴얼을 꼭 확인해 주세요.',
    notifHealthTitle: '🏥 보건증 만료 임박',
    notifHealthMsg: '보건증 만료일이 7일 남았습니다.\n보건소 방문 후 마이페이지에서 새 이미지를 업로드해주세요.',
    notifLeaveTitle: '✅ 휴무 승인 완료',
    notifLeaveMsg: '요청하신 6/3(수) 휴무 신청이 승인되어 스케줄에 반영되었습니다.',
    time10Min: '10분 전',
    time1Hour: '1시간 전',
    timeYesterday: '어제',
    time2Days: '2일 전',
    // 알림 화면
    notifListTitle: '알림 목록',
    markAllRead: '모두 읽음',
    delete: '삭제',
    confirm: '확인',
    // 프로필 수정 화면
    accountInfoReadonly: '계정 정보 (수정 불가)',
    idLabel: '아이디',
    unknown: '알 수 없음',
    branchLabel: '소속 지점',
    roleLabel: '권한 (직급)',
    adminRole: '관리자 (점주)',
    staffRole: '일반 직원',
    myInfoSection: '내 정보',
    nameLabel: '이름',
    namePlaceholder: '이름을 입력하세요',
    phoneLabel: '전화번호',
    phonePlaceholder: '예: 010-1234-5678',
    changePasswordSection: '비밀번호 변경',
    currentPasswordLabel: '현재 비밀번호',
    currentPasswordPlaceholder: '현재 비밀번호를 입력하세요',
    newPasswordLabel: '새 비밀번호',
    newPasswordPlaceholder: '변경할 비밀번호를 입력하세요',
    editCompleteBtn: '수정 완료',
    withdrawBtn: '회원 탈퇴',
    saveCompleteTitle: '저장 완료',
    saveCompleteMsg: '개인정보가 성공적으로 수정되었습니다.',
    editFailTitle: '수정 실패',
    editFailMsg: '정보를 수정하는 도중 에러가 발생했습니다.',
    // 대시보드 화면
    defaultUserName: '사용자',
    suffixNim: '님',
    qrCheckIn: 'QR출퇴근',
    expectedDailyWage: '예상 일급',
    currency: '원',
    noScheduleToday: '오늘은 근무 일정이 없습니다.',
    subReqAlertTitle: '대타 요청이 있습니다',
    subReqAlertDesc: '6월 03일 수요일 17:00 ~ 22:00 대타 가능하신가요?',
    applyBtn: '지원하기',
    rejectBtn: '거절',
    subReqConfirmTitle: '대타 지원 확인',
    subReqConfirmMsg: '6월 03일 수요일 17:00 ~ 22:00 대타를 지원하시겠습니까?',
    subApplySuccessTitle: '지원 완료',
    subApplySuccessMsg: '대타 지원이 완료되었습니다!\n점주님 승인 후 내 스케줄에 최종 반영됩니다.',
    boardDummy1Title: '가을 시즌 신메뉴 출시 안내',
    boardDummy1Content: '가을 시즌 신메뉴가 곧 출시됩니다!\n\n레시피 및 상세 매뉴얼은 추후 관리자가 업로드 할 예정이니 꼭 확인해 주세요.',
    boardDummy2Title: '보건증 만료 재확인 요청',
    boardDummy2Content: '안녕하세요, 점주입니다.\n\n최근 보건증 만료일이 도래하는 직원분들이 많습니다. 각자 마이페이지에서 보건증 유효기간을 확인하시고, 만료 전 반드시 보건소에 방문하시어 갱신해 주시기 바랍니다.',
    boardDummy3Title: '김선민, 서동윤, 김경민, 서동민 CAL 입사 경축',
    boardDummy3Content: '새로운 팀원 김선민, 서동윤, 김경민, 서동민님이 CAL에 합류하셨습니다!\n모두 반갑게 인사하며 따뜻한 환영 부탁드립니다. 🎉',
    boardDummy4Title: '마감 청소 매뉴얼 변경 안내',
    boardDummy4Content: '마감 청소 매뉴얼이 일부 변경되었습니다.\n자세한 내용은 포스기 옆에 부착된 새 매뉴얼을 확인해 주세요.',
    boardDummy5Title: '5월 우수 직원 선정 안내',
    boardDummy5Content: '5월 우수 직원으로 김선민 님이 선정되었습니다!\n김선민 님께는 소정의 상품이 지급될 예정입니다. 축하합니다.',
    boardDummy6Title: '여름 시즌 하계 유니폼 신청',
    boardDummy6Content: '여름 시즌을 맞아 반팔 유니폼을 추가 신청 받습니다.\n필요하신 분들은 이번 주 금요일까지 사이즈를 매니저에게 전달해 주세요.',
    // 게시판 카테고리 탭
    boardTabAll: '전체',
    boardTabNotice: '공지사항',
    boardTabMenu: '신메뉴',
    boardTabEvent: '이벤트',
    boardTabManual: '매뉴얼',
    boardTabLost: '분실물',
    badgeNew: 'NEW',
    badgeImportant: '중요!',
    // 대타 전용 화면
    substituteTitle: '대타 구하기 / 지원하기',
    subTabRequest: '대타 요청 목록',
    subTabHistory: '내 대타 이력',
    subPointTotal: '내 누적 인센티브 점수',
    subPointUnit: '점',
    subEmptyReq: '현재 올라온 대타 요청이 없습니다.',
    subEmptyHist: '아직 대타 이력이 없습니다.',

    // 문서 관리 화면
    uploadNew: '새 이미지 업로드',
    valid: '정상 (유효)',
    expired: '만료됨',
    needsRenewal: '갱신 요망',
    pendingApproval: '승인 대기',
    expiryDate: '만료일',
    startDate: '계약 시작일',
    wage: '시급',
    workPlace: '근무지',
  },
  '日本語': {
    greeting: 'こんにちは',
    admin: '管理者',
    staff: '一般スタッフ',
    todayWork: '今日の勤務',
    weeklyHours: '今週の勤務時間',
    weeklySalary: '今週の予想給与',
    notice: '社内掲示板',
    more: 'もっと見る',
    myInfo: '自分の情報管理',
    profileEdit: '個人情報の修正',
    contract: '私の労働契約書',
    healthCert: '保健証の管理',
    appSettings: 'アプリ設定',
    themeMode: '画面モード',
    languageSetting: '言語設定',
    pushAlert: 'アプリプッシュ通知',
    logout: 'ログアウト',
    scheduled: '勤務予定',
    inProgress: '勤務中',
    completed: '勤務完了',
    substituteReq: '代打探し中',
    offDay: '休み',
    leaveRequest: '休み申請 / 代打探し',
    noSchedule: '選択した日付の勤務予定はありません。',
    leaveReasonPlaceholder: '休みの理由を詳しく記入してください（例：通院、テストなど）',
    cancel: 'キャンセル',
    apply: '申請する',
    monthlyView: '月間ビュー',
    close: '閉じる',
    sun: '日',
    mon: '月',
    tue: '火',
    wed: '水',
    thu: '木',
    fri: '金',
    sat: '土',
    month: '月',
    year: '年',
    // 모달 및 탭 텍스트
    themeSettings: '画面モード設定',
    themeLight: 'ライトモード',
    themeDark: 'ダークモード',
    themeSystem: 'システム設定',
    langSettings: '言語設定',
    tabHome: 'ホーム',
    tabSchedule: 'スケジュール',
    tabNotif: '通知',
    tabMyPage: 'マイページ',
    tabAdminHome: '店舗管理',
    tabAdminSchedule: 'シフト管理',
    tabAdminSettings: '設定',
    // 알림 더미데이터 텍스트
    notifSubReqTitle: '🚨 代打リクエスト',
    notifSubReqMsg: '5月28日(水) 17:00~22:00の代打リクエストがあります。アプリで確認後、ご応募ください！',
    notifNoticeTitle: '📢 [お知らせ] 秋の新作メニュー発売',
    notifNoticeMsg: '秋の新作メニューがまもなく発売されます！\n\n掲示板でレシピや詳細マニュアルを必ずご確認ください。',
    notifHealthTitle: '🏥 保健証の有効期限間近',
    notifHealthMsg: '保健証の有効期限が残り7日です。\n保健所を訪問後、マイページから新しい画像をアップロードしてください。',
    notifLeaveTitle: '✅ 休み申請の承認完了',
    notifLeaveMsg: 'リクエストされた6/3(水)の休み申請が承認され、スケジュールに反映されました。',
    time10Min: '10分前',
    time1Hour: '1時間前',
    timeYesterday: '昨日',
    time2Days: '2日前',
    // 알림 화면
    notifListTitle: '通知リスト',
    markAllRead: 'すべて既読',
    delete: '削除',
    confirm: '確認',
    // 프로필 수정 화면
    accountInfoReadonly: 'アカウント情報（修正不可）',
    idLabel: 'ID',
    unknown: '不明',
    branchLabel: '所属店舗',
    roleLabel: '権限（役職）',
    adminRole: '管理者（店長）',
    staffRole: '一般スタッフ',
    myInfoSection: '自分の情報',
    nameLabel: '名前',
    namePlaceholder: '名前を入力してください',
    phoneLabel: '電話番号',
    phonePlaceholder: '例：090-1234-5678',
    changePasswordSection: 'パスワード変更',
    currentPasswordLabel: '現在のパスワード',
    currentPasswordPlaceholder: '現在のパスワードを入力してください',
    newPasswordLabel: '新しいパスワード',
    newPasswordPlaceholder: '変更するパスワードを入力してください',
    editCompleteBtn: '修正完了',
    withdrawBtn: '退会する',
    saveCompleteTitle: '保存完了',
    saveCompleteMsg: '個人情報が正常に修正されました。',
    editFailTitle: '修正失敗',
    editFailMsg: '情報の修正中にエラーが発生しました。',
    // 대시보드 화면
    defaultUserName: 'ユーザー',
    suffixNim: '様',
    qrCheckIn: 'QR出退勤',
    expectedDailyWage: '予想日給',
    currency: '円',
    noScheduleToday: '今日は勤務予定がありません。',
    subReqAlertTitle: '代打リクエストがあります',
    subReqAlertDesc: '6月03日(水) 17:00 ~ 22:00 代打可能ですか？',
    applyBtn: '応募する',
    rejectBtn: '拒否',
    subReqConfirmTitle: '代打応募の確認',
    subReqConfirmMsg: '6月03日(水) 17:00 ~ 22:00の代打に応募しますか？',
    subApplySuccessTitle: '応募完了',
    subApplySuccessMsg: '代打の応募が完了しました！\n店長の承認後、スケジュールに反映されます。',
    boardDummy1Title: '秋の新作メニュー発売のお知らせ',
    boardDummy1Content: '秋の新作メニューがまもなく発売されます！\n\nレシピや詳細マニュアルは後日管理者がアップロードする予定ですので、必ずご確認ください。',
    boardDummy2Title: '保健証の有効期限再確認のお願い',
    boardDummy2Content: 'こんにちは、店長です。\n\n最近、保健証の有効期限が近づいているスタッフが多くいます。各自マイページで有効期限を確認し、期限前に必ず保健所を訪問して更新してください。',
    boardDummy3Title: 'キム・ソンミン CAL入社のお祝い',
    boardDummy3Content: '新しいチームメンバーのキム・ソンミンさんがCALに加わりました！\n皆さん、温かい歓迎をよろしくお願いします。 🎉',
    boardDummy4Title: '締め作業マニュアル変更のご案内',
    boardDummy4Content: '締め作業のマニュアルが一部変更されました。\n詳細はレジ横に貼られている新しいマニュアルをご確認ください。',
    boardDummy5Title: '5月の優秀スタッフ選定のお知らせ',
    boardDummy5Content: '5月の優秀スタッフとしてキム・ミンスさんが選ばれました！\nキム・ミンスさんにはささやかな商品が贈られます。おめでとうございます。',
    boardDummy6Title: '夏期ユニフォーム申請',
    boardDummy6Content: '夏シーズンに向けて半袖ユニフォームの追加申請を受け付けます。\n必要な方は今週の金曜日までにサイズをマネージャーに伝えてください。',
    // 게시판 카테고리 탭
    boardTabAll: '全体',
    boardTabNotice: 'お知らせ',
    boardTabMenu: '新作メニュー',
    boardTabEvent: 'イベント',
    boardTabManual: 'マニュアル',
    boardTabLost: '忘れ物',
    badgeNew: 'NEW',
    badgeImportant: '重要！',
    // 대타 전용 화면
    substituteTitle: '代打探し / 応募',
    subTabRequest: '代打リクエストリスト',
    subTabHistory: '自分の代打履歴',
    subPointTotal: '累積インセンティブポイント',
    subPointUnit: 'pt',
    subEmptyReq: '現在、代打リクエストはありません。',
    subEmptyHist: 'まだ代打履歴がありません。',

    // 문서 관리 화면
    uploadNew: '新しい画像をアップロード',
    valid: '正常 (有効)',
    expired: '期限切れ',
    needsRenewal: '更新が必要',
    pendingApproval: '承認待ち',
    expiryDate: '有効期限',
    startDate: '契約開始日',
    wage: '時給',
    workPlace: '勤務地',
  },
  'English': {
    greeting: 'Hello',
    admin: 'Admin',
    staff: 'Staff',
    todayWork: 'Today\'s Shift',
    weeklyHours: 'Weekly Hours',
    weeklySalary: 'Expected Salary',
    notice: 'Notice Board',
    more: 'More',
    myInfo: 'My Info Management',
    profileEdit: 'Edit Profile',
    contract: 'My Contract',
    healthCert: 'Health Certificate',
    appSettings: 'App Settings',
    themeMode: 'Theme Mode',
    languageSetting: 'Language Settings',
    pushAlert: 'Push Notifications',
    logout: 'Logout',
    scheduled: 'Scheduled',
    inProgress: 'In Progress',
    completed: 'Completed',
    substituteReq: 'Finding Sub',
    offDay: 'Off',
    leaveRequest: 'Request Leave / Substitute',
    noSchedule: 'No schedule for the selected date.',
    leaveReasonPlaceholder: 'Please enter details for leave (e.g. sick, exam)',
    cancel: 'Cancel',
    apply: 'Apply',
    monthlyView: 'Monthly View',
    close: 'Close',
    sun: 'Sun',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    month: 'Month',
    year: 'Year',
    // 모달 및 탭 텍스트
    themeSettings: 'Theme Settings',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    themeSystem: 'System Default',
    langSettings: 'Language Settings',
    tabHome: 'Home',
    tabSchedule: 'Schedule',
    tabNotif: 'Notifications',
    tabMyPage: 'My Page',
    tabAdminHome: 'Store Mgmt',
    tabAdminSchedule: 'Schedule Mgmt',
    tabAdminSettings: 'Settings',
    // 알림 더미데이터 텍스트
    notifSubReqTitle: '🚨 Substitute Request',
    notifSubReqMsg: 'There is a substitute request for Wed, May 28, 17:00~22:00. Please check and apply!',
    notifNoticeTitle: '📢 [Notice] Fall Season New Menu',
    notifNoticeMsg: 'The new fall season menu will be released soon!\n\nPlease check the recipe and manual on the board.',
    notifHealthTitle: '🏥 Health Cert Expiring Soon',
    notifHealthMsg: 'Your health certificate expires in 7 days.\nPlease visit the health center and upload a new image.',
    notifLeaveTitle: '✅ Leave Approved',
    notifLeaveMsg: 'Your leave request for 6/3(Wed) has been approved and applied to your schedule.',
    time10Min: '10 mins ago',
    time1Hour: '1 hour ago',
    timeYesterday: 'Yesterday',
    time2Days: '2 days ago',
    // 알림 화면
    notifListTitle: 'Notifications',
    markAllRead: 'Mark all as read',
    delete: 'Delete',
    confirm: 'Confirm',
    // Profile Edit Screen
    accountInfoReadonly: 'Account Info (Read-Only)',
    idLabel: 'ID',
    unknown: 'Unknown',
    branchLabel: 'Branch',
    roleLabel: 'Role (Position)',
    adminRole: 'Admin (Manager)',
    staffRole: 'Staff',
    myInfoSection: 'My Info',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'e.g. 123-456-7890',
    changePasswordSection: 'Change Password',
    currentPasswordLabel: 'Current Password',
    currentPasswordPlaceholder: 'Enter current password',
    newPasswordLabel: 'New Password',
    newPasswordPlaceholder: 'Enter new password',
    editCompleteBtn: 'Save Changes',
    withdrawBtn: 'Delete Account',
    saveCompleteTitle: 'Saved',
    saveCompleteMsg: 'Profile successfully updated.',
    editFailTitle: 'Update Failed',
    editFailMsg: 'An error occurred while updating.',
    // Dashboard Screen
    defaultUserName: 'User',
    suffixNim: '',
    qrCheckIn: 'QR Check-In',
    expectedDailyWage: 'Est. Daily Wage',
    currency: 'KRW',
    noScheduleToday: 'No schedule for today.',
    subReqAlertTitle: 'Substitute Request',
    subReqAlertDesc: 'Are you available to sub on Wed, Jun 3, 17:00~22:00?',
    applyBtn: 'Apply',
    rejectBtn: 'Decline',
    subReqConfirmTitle: 'Confirm Application',
    subReqConfirmMsg: 'Apply for the substitute shift on Wed, Jun 3, 17:00~22:00?',
    subApplySuccessTitle: 'Application Complete',
    subApplySuccessMsg: 'Application submitted!\nIt will be added to your schedule upon manager approval.',
    boardDummy1Title: 'Fall Season New Menu Release',
    boardDummy1Content: 'The new fall season menu will be released soon!\n\nRecipes and detailed manuals will be uploaded shortly by the admin. Please check back.',
    boardDummy2Title: 'Health Certificate Expiration Notice',
    boardDummy2Content: 'Hello from the manager.\n\nMany staff members have expiring health certificates. Please check your expiration date on My Page and renew it at the health center before it expires.',
    boardDummy3Title: 'Welcome Seonmin Kim to CAL',
    boardDummy3Content: 'A new team member, Seonmin Kim, has joined CAL!\nLet\'s all give a warm welcome. 🎉',
    boardDummy4Title: 'Closing Cleaning Manual Update',
    boardDummy4Content: 'The closing cleaning manual has been partially updated.\nPlease check the new manual attached next to the POS machine for details.',
    boardDummy5Title: 'May Employee of the Month',
    boardDummy5Content: 'Minsu Kim has been selected as the Employee of the Month for May!\nA small gift will be awarded to Minsu Kim. Congratulations!',
    boardDummy6Title: 'Summer Uniform Request',
    boardDummy6Content: 'We are taking additional requests for short-sleeve uniforms for the summer season.\nIf you need one, please give your size to the manager by this Friday.',
    // Board Category Tabs
    boardTabAll: 'All',
    boardTabNotice: 'Notice',
    boardTabMenu: 'New Menu',
    boardTabEvent: 'Event',
    boardTabManual: 'Manual',
    boardTabLost: 'Lost & Found',
    badgeNew: 'NEW',
    badgeImportant: 'Important!',
    // Substitute Screen
    substituteTitle: 'Substitute / Apply',
    subTabRequest: 'Substitute Requests',
    subTabHistory: 'My Sub History',
    subPointTotal: 'Accumulated Incentive Points',
    subPointUnit: 'pt',
    subEmptyReq: 'There are no substitute requests currently.',
    subEmptyHist: 'No substitute history yet.',

    // 문서 관리 화면
    uploadNew: 'Upload New Image',
    valid: 'Valid',
    expired: 'Expired',
    needsRenewal: 'Needs Renewal',
    pendingApproval: 'Pending Approval',
    expiryDate: 'Expiry Date',
    startDate: 'Start Date',
    wage: 'Hourly Wage',
    workPlace: 'Workplace',
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: '한국어',
  setLanguage: () => {},
  t: (key: string) => key, // Provider가 없을 경우 key를 그대로 반환하여 에러 방지
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('한국어');

  // key 값을 받아 현재 선택된 언어의 텍스트를 반환하는 번역 함수
  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['한국어']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);