CREATE TABLE ATTENDANCE (

    ID VARCHAR2(21 CHAR) PRIMARY KEY,

    STORE_ID VARCHAR2(21 CHAR) NOT NULL,

    USER_ID VARCHAR2(21 CHAR) NOT NULL,

    SHIFT_ID VARCHAR2(21 CHAR),

    WORK_DATE DATE NOT NULL,

    CHECK_IN_AT TIMESTAMP,

    CHECK_OUT_AT TIMESTAMP,

    WORK_MINUTES NUMBER DEFAULT 0,

    OVERTIME_MINUTES NUMBER DEFAULT 0,

    STATUS VARCHAR2(20 CHAR)

);
CREATE TABLE ATTENDANCE_QR (

                               QR_TOKEN VARCHAR2(100 CHAR) PRIMARY KEY,

                               STORE_ID VARCHAR2(21 CHAR) NOT NULL,

                               CREATED_AT TIMESTAMP NOT NULL,

                               EXPIRED_AT TIMESTAMP NOT NULL,

                               IS_ACTIVE CHAR(1) DEFAULT 'Y'

);

select * from ATTENDANCE;

commit;

delete from ATTENDANCE where store_id = 'V1StGXR8_Z5jdHi6B-myT';



