CREATE TABLE FILES (
                       ID              VARCHAR2(21 CHAR) PRIMARY KEY,

                       USER_ID         VARCHAR2(21 CHAR)
        REFERENCES USERS(ID),

                       STORE_ID        VARCHAR2(21 CHAR),

                       FILE_TYPE       VARCHAR2(30 CHAR) NOT NULL,

                       ORIGINAL_NAME   VARCHAR2(255 CHAR),

                       STORAGE_PATH    VARCHAR2(500 CHAR) NOT NULL,

                       FILE_SIZE       NUMBER,


                       MIME_TYPE       VARCHAR2(100 CHAR),

                       STATUS          VARCHAR2(20 CHAR) DEFAULT 'PENDING',
                       OCR_STATUS      VARCHAR2(20 CHAR) DEFAULT 'PENDING',
                       EXPIRY_DATE     DATE,
                       NOTES           VARCHAR2(1000 CHAR),
                       EXTRACTED_DATA  CLOB,

                       CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
                       UPDATED_AT      TIMESTAMP
);

-- Existing DB migration: run these only if FILES already exists.
-- ALTER TABLE FILES ADD STORE_ID VARCHAR2(21 CHAR);
-- ALTER TABLE FILES ADD STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
-- ALTER TABLE FILES ADD OCR_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
-- ALTER TABLE FILES ADD EXPIRY_DATE DATE;
-- ALTER TABLE FILES ADD NOTES VARCHAR2(1000 CHAR);
-- ALTER TABLE FILES ADD EXTRACTED_DATA CLOB;

ALTER TABLE FILES ADD STORE_ID VARCHAR2(21 CHAR);
ALTER TABLE FILES ADD STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
ALTER TABLE FILES ADD OCR_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
ALTER TABLE FILES ADD EXPIRY_DATE DATE;
ALTER TABLE FILES ADD NOTES VARCHAR2(1000 CHAR);
ALTER TABLE FILES ADD EXTRACTED_DATA CLOB;




--dddd


-- 1. 직원 시급 설정
UPDATE STORE_MEMBER
SET PAY_TYPE = 'HOURLY',
    PAY_AMOUNT = 10000
WHERE STORE_ID = 'V1StGXR8_Z5jdHi6B-myT'
  AND USER_ID = 'U2xY8pQ3_a1BcDeFgH1j2';

-- 2. 2026년 6월 근태 데이터 추가
INSERT INTO ATTENDANCE (
    ID,
    STORE_ID,
    USER_ID,
    SHIFT_ID,
    WORK_DATE,
    CHECK_IN_AT,
    CHECK_OUT_AT,
    WORK_MINUTES,
    OVERTIME_MINUTES,
    STATUS
)
VALUES (
           'ATT_PAY_TEST_001',
           'V1StGXR8_Z5jdHi6B-myT',
           'U2xY8pQ3_a1BcDeFgH1j2',
           NULL,
           DATE '2026-06-22',
           TIMESTAMP '2026-06-22 18:00:00',
           TIMESTAMP '2026-06-23 04:00:00',
           600,
           120,
           'CHECKED_OUT'
       );

COMMIT;