CREATE TABLE FILES (
                       ID              VARCHAR2(21 CHAR) PRIMARY KEY,

                       USER_ID         VARCHAR2(21 CHAR)
        REFERENCES USERS(ID),

                       STORE_ID        VARCHAR2(21 CHAR),

                       FILE_TYPE       VARCHAR2(30 CHAR) NOT NULL,

                       ORIGINAL_NAME   VARCHAR2(255 CHAR),

                       STORAGE_PATH    VARCHAR2(500 CHAR) NOT NULL,

                       FILE_SIZE       NUMBER,


                       MIME_TYPE       VARCHAR2(100 CHAR),

                       STATUS          VARCHAR2(20 CHAR) DEFAULT 'PENDING',
                       OCR_STATUS      VARCHAR2(20 CHAR) DEFAULT 'PENDING',
                       EXPIRY_DATE     DATE,
                       NOTES           VARCHAR2(1000 CHAR),
                       EXTRACTED_DATA  CLOB,

                       CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
                       UPDATED_AT      TIMESTAMP
);

-- Existing DB migration: run these only if FILES already exists.
-- ALTER TABLE FILES ADD STORE_ID VARCHAR2(21 CHAR);
-- ALTER TABLE FILES ADD STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
-- ALTER TABLE FILES ADD OCR_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
-- ALTER TABLE FILES ADD EXPIRY_DATE DATE;
-- ALTER TABLE FILES ADD NOTES VARCHAR2(1000 CHAR);
-- ALTER TABLE FILES ADD EXTRACTED_DATA CLOB;

ALTER TABLE FILES ADD STORE_ID VARCHAR2(21 CHAR);
ALTER TABLE FILES ADD STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
ALTER TABLE FILES ADD OCR_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING';
ALTER TABLE FILES ADD EXPIRY_DATE DATE;
ALTER TABLE FILES ADD NOTES VARCHAR2(1000 CHAR);
ALTER TABLE FILES ADD EXTRACTED_DATA CLOB;