CREATE TABLE PEOPLE_LOG (
                            ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                            STORE_ID VARCHAR2(50) NOT NULL,
                            RECORD_TIME TIMESTAMP NOT NULL,
                            PEOPLE_COUNT NUMBER NOT NULL
);

CREATE INDEX IDX_PEOPLE_LOG_01
    ON PEOPLE_LOG(STORE_ID, RECORD_TIME);

INSERT INTO PEOPLE_LOG (STORE_ID, RECORD_TIME, PEOPLE_COUNT)
SELECT
    'STORE001',
    TO_TIMESTAMP('2026-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
        + NUMTODSINTERVAL((LEVEL - 1) * 10, 'MINUTE'),
    TRUNC(DBMS_RANDOM.VALUE(1, 35))
FROM DUAL
    CONNECT BY LEVEL <= 144;

ALTER TABLE PEOPLE_LOG
    ADD CAMERA_ID VARCHAR2(50);
UPDATE PEOPLE_LOG
SET CAMERA_ID = 'CAM-001'
WHERE CAMERA_ID IS NULL;

COMMIT;
ALTER TABLE PEOPLE_LOG
    MODIFY CAMERA_ID VARCHAR2(50) NOT NULL;
select * from people_log;