    CREATE TABLE USER_LINE
    (
        USER_ID VARCHAR2(21 CHAR) PRIMARY KEY,
        LINE_USER_ID VARCHAR2(100 CHAR) UNIQUE NOT NULL,
        FOLLOW_YN CHAR(1) DEFAULT 'N'
    );

select * from user_line;

